project: 
  type: website

website: 
  page-navigation: true
  title: "Projeto MPB" 
  site-url: "https://projetompb.github.io/site/"
  repo-url: "https://github.com/ProjetoMPB/site"
  repo-actions: [edit, source, issue]
  favicon: favicon.ico
  
  page-footer:
    right: "Página construída em [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: logos/logo-projeto.png
    favicon: favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://projetompb.github.io/site/
        text: "Projeto MPB"
      - icon: github
        href: https://github.com/ProjetoMPB/site
        text: "Projeto MPB (repositório)"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Página inicial
      - href: capitulos/intro.qmd
        text: Introdução
      - href: capitulos/nossa-mpb.qmd
        text: A "nossa" MPB
      - href: capitulos/estilo-musical.qmd
        text: Uma breve discussão sobre estilo musical
      - href: capitulos/hipoteses.qmd
        text: Hipóteses
      - href: capitulos/corpora-mpb.qmd
        text: Os *corpora* MPB
      - href: capitulos/modelos-teoricos.qmd
        text: Modelos teóricos
      - text: "---"
      - href: capitulos/listagem-corpora.qmd
        text: Listagem dos *corpora*
      - href: capitulos/producao-bibliografica.qmd
        text: Produção bibliográfica

crossref:
  fig-title: Figura
  tbl-title: Tabela

lang: pt

bibliography: refs.bib

# number-sections: true

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto