---
title: Atributos primários de avaliação
---
Os atributos (e métricas) que adotamos para a avaliação das análises podem ter natureza quantitativa ou qualitativa, bem como podem ser associados a *marcadores estilísticos* (ver o capítulo sobre estilo musical). 

Buscando um refinamento, classificamos os atributos em duas categorias básicas, *primários* e *secundários*. A principal diferença entre essas categorias reside no fato de que, enquanto os atributos secundários são *potenciais* definidores de estilo, os primários, ainda que importantes, não apresentam, individualmente, essa capacidade (apenas se vistos em conjunto). Na verdade, os atributos secundários, por assim dizer, "revisam" atributos primários a eles correspondentes, examinando-os de outras perspectivas, em geral mais amplas e, ao mesmo tempo, detalhadas. Podemos ainda considerar, de um modo um pouco mais livre, que os atributos secundários detalham os *contextos* nos quais os atributos primários se inserem.

As duas classes de atributos, por sua vez, segmentam-se internamente em relação aos *domínios* (harmonia e melodia), a *níveis* de organização e a *aspectos* específicos desses níveis. Para uma mais rápida identificação, os aspectos são rotulados de acordo com a fórmula "mXnp", onde *m* é o número que indica o nível do atributo -- primário (m = 1) ou secundário (m = 2) --, *X* é a letra que representa o domínio considerado (H, para harmonia, M, para melodia), *n* é o número do nível em questão (n = 1, 2, 3 ou 4) e *p* é uma letra sequencial em caixa baixa identificadora do aspecto específico (p = a, b, c, d, ...). Assim, por exemplo, o rótulo 1H3b corresponde a um atributo estilístico primário (1) associado ao domínio da harmonia (H) associado ao terceiro nível (3, que é referente aos tipos acordais), considerando o segundo aspecto (b, que se refere à categoria funcional mais recorrente dentro do *corpus* em análise).

---

Por hipótese, os **atributos primários** evidenciam especialmente (mas não apenas) elementos estruturais compartilhados por compositores pertencentes a um determinado superconjunto estilístico. Foram definidos 35 atributos primários ao longo deste estudo, 19 associados ao domínio harmônico e 16 ao domínio melódico. São as seguintes suas descrições básicas:

### ATRIBUTOS PRIMÁRIOS HARMÔNICOS
**1H1** -- nível das tonalidades (contém cinco aspectos):

- 1H1a -- informa o número de tonalidades distintas empregadas dentro de cada *corpus* (bem como o percentual diante do total possível -- 24), incluindo principais e secundárias (ou seja, aquelas obtidas por modulação interna).
- 1H1b -- identifica a tônica mais recorrente. Por convenção, maiúsculas indicam tonalidades maiores (DÓ, SOL etc.) e minúsculas as menores (ré, sib etc.). O atributo indica ainda o percentual de sua ocorrência.  
- 1H1c -- informa a distribuição percentual das tonalidades principais em modo maior.         
- 1H1d -- informa a distribuição percentual de peças monotônicas (em oposição às pluritônicas).             
- 1H1e -- identifica a relação binária tonal (RBT) mais recorrente, incluindo sua frequência percentual. 

---

**1H2** -- nível das funções (contém dois aspectos):

- 1H2a -- identifica a categoria funcional mais recorrente, incluindo sua distribuição percentual.  
- 1H2b -- identifica a relação binária funcional (RBF) mais recorrente, incluindo sua distribuição percentual.    

---

**1H3** -- nível dos tipos acordais (contém três aspectos):

- 1H3a -- informa o *genus* de tipos acordais mais recorrente, incluindo sua distribuição percentual.  
- 1H3b -- identifica o tipo acordal mais recorrente, incluindo sua distribuição percentual.         
- 1H3c -- identifica a relação binária abstrata (RBA) mais recorrente, incluindo sua distribuição percentual.

---

**1H4** -- nível dos acordes específicos (contém quatro aspectos):

- 1H4a -- informa a distribuição percentual de acordes em estado fundamental (em relação aos invertidos). 
- 1H4b -- informa o número de acordes específicos distintos empregados.     
- 1H4c -- identifica o acorde específico mais recorrente, incluindo sua distribuição percentual.        
- 1H4d -- identifica o movimento intervalar de baixos mais recorrente entre acordes contíguos, incluindo sua distribuição percentual.   

------

### ATRIBUTOS PRIMÁRIOS MELÓDICOS
**1M1** -- nível das notas-funções (contém quatro aspectos):

- 1M1a -- identifica o grau escalar mais recorrente, considerando os modos maior e menor, informando seus percentuais em relação ao total de casos.
- 1M1b -- identifica a categoria de nota-função mais recorrente (neste caso, englobando ambos os modos), informando sua distribuição percentual.           
- 1M1c -- identifica a nota-estrutural mais recorrente (englobando ambos os modos), informando sua distribuição percentual.           
- 1M1d -- informa o índice de ancoragem (ia) médio do *corpus*.   

---

**1M2** -- nível do contorno melódico (contém cinco aspectos):
- 1M2a -- identifica a c-letra mais recorrente, informando sua distribuição percentual.     
- 1M2b -- identifica a c-palavra mais recorrente, informando sua distribuição percentual. 
- 1M2c -- identifica a cardinalidade de c/r palavra mais recorrente, informando sua distribuição percentual.  
- 1M2d -- informa o índice de economia intervalar (iE) médio do *corpus*. .
- 1M2e -- informa o índice de economia intervalar compensada (iEc) médio do *corpus*. . 

---

**1M3** -- nível do ritmo (contém quatro aspectos):
- 1M3a -- identifica o ponto de ataque mais recorrente do perfil métrico, informando sua distribuição percentual.    
- 1M3b -- identifica a r-letra mais recorrente, informando sua distribuição percentual. 
- 1M3c -- identifica a r-palavra mais recorrente, informando sua distribuição percentual.  
- 1M3d -- informa o índice de contrametricidade (ic) médio do *corpus*. .

---------------------------------

## RESULTADOS - Fase 1 (compositores 1 a 10)

(falar sobre os quadros) ......................

|                          |           |
|--------------------------|-----------|
| \multicolumn{5}{l|}{1H1} |           |
| \multicolumn{2}{l|}{1H2} |           |
| \multicolumn{3}{l|}{1H3} |           |
| \textit{Corpus}          | a         | b            | c    | d    | e                   | a        | b          | a        | b         | c           | a    | b   | c           | d        |
| Jazz                     | 16 (66.7) | DÓ (26.5)    | 83.7 | 46.0 | M4M (18.6)          | I (19.6) | V|I (11.2) | Y (37.0) | Y0 (20.0) | z|5Y (16.8) | 98.7 | 241 | Gm7 (3.3)   | 5 (49.3) |
| Choro                    | 9 (37.5)  | FÁ (36.0)    | 72.0 | -    | M5M (29.0)          | I (27.8) | V|I (15.7) | Y (43.0) | v0 (42.3) | Y|5v (13.9) | 77.7 | 89  | F (9.1)     | 5 (33.6) |
| Samba                    | 18 (75.0) | SOL (18.0)   | 80.0 | 86.0 | M9m (38.5)          | I (28.6) | V|I (17.1) | Y (45.6) | Y0 (44.7) | Y|5V (15.2) | 74.3 | 85  | G7 (7.6)    | 5 (38.1) |
| Tom Jobim                | 15 (62.5) | DÓ (20.0)    | 76.0 | 52.0 | M3M (11.5)          | I (20.1) | V|I (5.6)  | Y (36.1) | z0 (17.6) | z|5Y (9.0)  | 92.2 | 360 | Dm7 (3.6)   | 5 (32.4) |
| Ivan Lins                | 15 (62.5) | LÁ (16.0)    | 84.0 | 40.0 | M3M (16.3)          | I (20.8) | V|I (7.0)  | Y (41.3) | z2 (10.4) | Y|0Y (12.3) | 88.1 | 337 | Bm7.9 (1.9) | 5 (33.1) |
| Chico Buarque            | 12 (50.0) | DÓ (18.4)    | 69.4 | 60.0 | M9m (14.9)          | V (17.3) | V|I (9.1)  | Y (42.3) | Y0 (20.4) | z|5Y (8.6)  | 78.4 | 230 | A7 (4.3)    | 5 (30.4) |
| Edu Lobo                 | 18 (75.0) | DÓ/RÉ (12.0) | 54.0 | 44.0 | M4M (12.2)          | I (22.7) | V|I (8.8)  | Y (39.2) | z0 (11.7) | z|5Y (8.0)  | 83.8 | 366 | Am7 (2.7)   | 5 (24.1) |
| Caetano Veloso           | 17 (70.8) | DÓ (26.0)    | 84.0 | 58.0 | M10M (12.2)         | I (23.2) | V|I (12.5) | Y (34.3) | V0 (23.3) | z|5Y (12.5) | 96.5 | 167 | C (6.1)     | 5 (43.5) |
| Djavan                   | 12 (50.0) | RÉ/LÁ (15.7) | 74.5 | 62.7 | M10M/M9m/m8M (10.0) | I (19.3) | V|I (8.2)  | Y (39.4) | z0 (16.3) | z|5Y (10.0) | 93.4 | 230 | Am7 (3.1)   | 5 (36.9) |
| João Bosco               | 10 (41.7) | RÉ (18.0)    | 56.0 | 74.0 | M0m (15.1)          | I (24.4) | V|I (9.6)  | Y (39.8) | Y0 (13.8) | Y|5Y (7.6)  | 91.1 | 276 | B7 (3.4)    | 5 (31.4) |
| Milton Nascimento        | 14 (58.3) | ré (20.0)    | 52.0 | 60.0 | M7M/M0m/m0M (9.3)   | I (35.4) | V|I (7.7)  | V (30.1) | V0 (25.2) | V|7V (4.2)  | 71.7 | 217 | G (6.2)     | 0 (29.4) |
| Gilberto Gil             | 14 (58.3) | DÓ (18.0)    | 84.0 | 54.0 | M9m (13.2)          | I (24.6) | V|I (9.8)  | Y (43.0) | Y0 (23.3) | Y|5Y (8.3)  | 92.8 | 207 | A7 (3.9)    | 5 (35.3) |
| Rita Lee                 | 14 (58.3) | LÁ (19.6)    | 64.7 | 74.5 | M5M (17.9)          | I (24.9) | V|I (9.7)  | Y (38.6) | V0 (29.0) | z|5Y (8.2)  | 96.2 | 147 | A (5.5)     | 5 (32.7) |
