---
title: Atributos primários e secundários de avaliação -- descrição
---

## Introdução

Os atributos (e métricas) que adotamos para a avaliação das análises podem ter natureza quantitativa ou qualitativa, bem como podem ser associados a *marcadores estilísticos* (ver Capítulo sobre [Estilo Musical](estilo-musical.qmd)). 

Buscando um refinamento, classificamos os atributos em três categorias básicas, *primários*, *secundários* e *terciários* (em desenvolvimento). As principais diferenças entre essas categorias se encontram nos seus respectivos graus de complexidade e detalhamento, bem como no quanto contribuem para evidenciar questões e demarcações estilísticas. Assim, enquanto os atributos secundários são *potenciais* definidores de estilo, os primários, ainda que importantes, não apresentam, tão marcadamente essa capacidade (apenas se vistos em conjunto). Na verdade, os atributos secundários, por assim dizer, "revisam" atributos primários a eles correspondentes, examinando-os de outras perspectivas, em geral mais amplas e, ao mesmo tempo, detalhadas. Podemos ainda considerar, de um modo um pouco mais livre, que os atributos secundários evidenciam os *contextos* nos quais os atributos primários se inserem. Por sua vez, atributos terciários podem ser vistos como uma espécie de sintonia fina dos secundários, tendo como principais características a natureza eminente quantitativa e o fato de considerarem todo o conjunto de cada um de seus atributos (enquanto os secundários envolvem mais seus aspectos qualitativos).

## Critérios de nomenclatura para atributos primários e secundários^[Os atributos terciários são identificados com uma simbologia distinta.] 

Os atributos primários e secundários são agrupadas internamente em relação aos *domínios* (harmonia e melodia),^[O domínio melódico, por sua vez, subdivide-se em subdomínios: notas-funções, alturas e ritmo.] a *níveis* de organização e a *aspectos* específicos desses níveis. Para uma rápida identificação, os aspectos são rotulados de acordo com a fórmula "mXnp", onde *m* é o número que indica o nível do atributo -- primário (m = 1) ou secundário (m = 2) --, *X* é a letra que representa o domínio considerado (H, para harmonia, M, para melodia), *n* é o número do nível em questão (n = 1, 2, 3 ou 4) e *p* é uma letra sequencial em caixa baixa identificadora do aspecto específico (p = a, b, c, d, ...). Assim, por exemplo, o rótulo 1H3b corresponde a um atributo estilístico *primário* (1) vinculado ao domínio da *harmonia* (H) associado ao *terceiro nível* (3, que é referente aos tipos acordais), considerando o *segundo aspecto* (b, que se refere à categoria funcional mais recorrente dentro do *corpus* em análise).

## Atributos primários

Por hipótese, os atributos primários evidenciam especialmente (mas não apenas) elementos estruturais compartilhados por compositores pertencentes a um determinado superconjunto estilístico. Foram definidos 35 atributos primários, 19 associados ao domínio harmônico e 16 ao domínio melódico. São as seguintes suas descrições básicas:

### Atributos primários harmônicos

**1H1** -- nível das tonalidades (contém cinco aspectos):

- 1H1a -- informa o número de tonalidades distintas empregadas dentro de cada *corpus* (bem como o percentual diante do total possível -- 24), incluindo principais e secundárias (ou seja, aquelas obtidas por modulação interna).
- 1H1b -- identifica a tônica mais recorrente. Por convenção, maiúsculas indicam tonalidades maiores (DÓ, SOL etc.) e minúsculas as menores (ré, si♭ etc.). O atributo indica ainda o percentual de sua ocorrência.  
- 1H1c -- informa a distribuição percentual das tonalidades principais em modo maior.         
- 1H1d -- informa a distribuição percentual de peças monotônicas (em oposição às pluritônicas).             
- 1H1e -- identifica a relação binária tonal (RBT) mais recorrente, incluindo sua frequência percentual. 

---

**1H2** -- nível das funções (contém dois aspectos):

- 1H2a -- identifica a categoria funcional mais recorrente, incluindo sua distribuição percentual.  
- 1H2b -- identifica a relação binária funcional (RBF) mais recorrente, incluindo sua distribuição percentual.    

---

**1H3** -- nível dos tipos acordais (contém três aspectos):

- 1H3a -- informa o *genus* de tipos acordais mais recorrente, incluindo sua distribuição percentual.  
- 1H3b -- identifica o tipo acordal mais recorrente, incluindo sua distribuição percentual.         
- 1H3c -- identifica a relação binária abstrata (RBA) mais recorrente, incluindo sua distribuição percentual.

---

**1H4** -- nível dos acordes específicos (contém quatro aspectos):

- 1H4a -- informa a distribuição percentual de acordes em estado fundamental (em relação aos invertidos). 
- 1H4b -- informa o número de acordes específicos distintos empregados.     
- 1H4c -- identifica o acorde específico mais recorrente, incluindo sua distribuição percentual.        
- 1H4d -- identifica o movimento intervalar de baixos mais recorrente entre acordes contíguos, incluindo sua distribuição percentual.   

---

### Atributos primários melódicos

**1M1** -- nível das notas-funções (contém quatro aspectos):

- 1M1a -- identifica o grau escalar mais recorrente, considerando os modos maior e menor, informando seus percentuais em relação ao total de casos.
- 1M1b -- identifica a categoria de nota-função mais recorrente (neste caso, englobando ambos os modos), informando sua distribuição percentual.           
- 1M1c -- identifica a nota-estrutural mais recorrente (englobando ambos os modos), informando sua distribuição percentual.           
- 1M1d -- informa o índice de ancoragem (ia) médio do *corpus*.   

---

**1M2** -- nível do contorno melódico (contém cinco aspectos):

- 1M2a -- identifica a c-letra mais recorrente, informando sua distribuição percentual.     
- 1M2b -- identifica a c-palavra mais recorrente, informando sua distribuição percentual. 
- 1M2c -- identifica a cardinalidade de c/r palavra mais recorrente, informando sua distribuição percentual.  
- 1M2d -- informa o índice de economia intervalar (iE) médio do *corpus*. .
- 1M2e -- informa o índice de economia intervalar compensada (iEc) médio do *corpus*. . 

---

**1M3** -- nível do ritmo (contém quatro aspectos):

- 1M3a -- identifica o ponto de ataque mais recorrente do perfil métrico, informando sua distribuição percentual.    
- 1M3b -- identifica a r-letra mais recorrente, informando sua distribuição percentual. 
- 1M3c -- identifica a r-palavra mais recorrente, informando sua distribuição percentual.  
- 1M3d -- informa o índice de contrametricidade (ic) médio do *corpus*.

---

## Atributos secundários

Os atributos secundários são essencialmente revisões (ou detalhamentos) de alguns atributos primários, de maneira a permitir a evidenciação de características peculiares de um(a) determinado(a) compositor(a) (ou de um pequeno grupo de compositores) em relação a um contexto estilístico mais amplo. Exposto de outro modo, enquanto atributos primários tendem a agrupar *corpora* (e os estilos composicionais a eles associados) formando superconjuntos, os secundários agem principalmente na segregação desses subconjuntos, tendendo a promover fronteiras estilísticas entre compositores. Além dessa diferença, ao contrário do que acontece com os primários, os atributos secundários geralmente são vinculados a hipóteses, a partir de conhecimentos informais pré-existentes.

### Atributos secundários harmônicos

**2H1** -- nível das relações tonais (contém três aspectos):

- 2H1a -- informa a quantidade de relações binárias tonais (RBTs) distintas em cada *corpus*. A princípio, não é associado objetivamente a uma hipótese, tendo em vista que uma diversidade de RBTs não implica necessariamente maior complexidade. Os próximos atributos atuam nesse sentido, na busca de qualificar os tipos de relações e apresentar hipóteses mais consistentes.   

- 2H1b -- compara a distribuição das relações binárias tonais da superclasse "notáveis" com o restante do universo. Por hipótese, RBTs "não notáveis" são mais empregadas no contexto estilístico da MPB do que as "notáveis". Assim, uma predominância de RBTs "notáveis" em um determinado *corpus* tenderia, potencialmente, a "afastá-lo"  do subconjunto-alvo.

- 2H1c -- examina em maiores detalhes os conteúdos das superclasses, considerando a distribuição de sete classes de RBTs, as "notáveis" HOM, REL, D/SD e as "não notáveis" MED, QUA, STM, TOM, TRI. Por hipótese, a predominância da classe MED é um indicativo de pertencimento ao subconjunto-alvo, ou seja, um *marcador estilístico centrípeto* (ver [capítulo sobre estilo musical](estilo-musical.qmd)).

---

**2H2** -- nível dos tipos acordais (contém quatro aspectos):

- 2H2a -- informa a quantidade de tipos acordais (TAs) distintos em cada *corpus*, bem como seu percentual em relação ao total, de acordo com o modelo GTA (ver [capítulo sobre os modelos teóricos](modelos-teoricos.qmd)). Por hipótese, a  diversidade de TAs seria um possível marcador centrípeto (também em relação ao subconjunto JAZZ).

- 2H2b -- compara a distribuição dos conteúdos dos 10 *genera* de tipos acordais. Por hipótese, uma alta recorrência dos *genera* triádicos V, v em relação aos demais se torna um marcador estilístico *centrífugo*. Inversamente, uma distribuição mais significativa dos *genera* Z, z (independentemente dos demais) indicaria um marcador centrípeto. No entanto, este aspecto também seria característico do subconjunto JAZZ, demandando observações complementares para o refinamento da análise.

- 2H2c -- compara as distribuições relativas de protoacordes e variantes acordais, agrupados. Por hipótese, o estilo MPB se caracteriza por uma significativa presença de tipos acordais variantes, em relação aos protoacordes, o que não se observaria tão intensamente no subconjunto JAZZ, constituindo , portanto, um possível fator diferenciador entre os dois contextos.

- 2H2d -- refina o atributo 2H2c, diferenciando protoacordes e variantes de acordo com os respectivos *genera*.   

---

**2H3** -- nível das funções (contém cinco aspectos):

- 2H3a -- informa a quantidade de categorias funcionais distintas em cada *corpus* e o respectivo percentual considerando o total de categorias adotadas (73). Por hipótese, a  diversidade de categorias seria um marcador estilístico centrípeto (também em relação ao subconjunto JAZZ).

- 2H3b -- compara a distribuição de 12 classes (e/ou subclasses) mais significativas de categorias funcionais, a saber, DIA,  DS, SubV, DIM, D-pte, E1 e E2.

- 2H3c -- refina o atributo 2H3b, examinando os conteúdos de cada classe, em separado.

- 2H3d -- compara as classes de relações binárias funcionais, ou RBFs de alto-nível (DIA|DIA, CR|DIA, DIA|CR, CR|CR). Por hipótese, integrantes do subconjunto-alvo e do subconjunto JAZZ apresentariam distribuições significativas das classes que envolvam a categoria CR. A separação dos dois subconjuntos neste atributo requererá, por certo, exames e discussões suplementares.  

- 2H3e -- dispõe a distribuição das relações binárias funcionais de alto nível (considerando as classes de RBFs [ver capítulo dos Modelos Teóricos](modelos-teoricos.qmd).

---------------

### Atributos secundários melódicos

**2M1** -- nível das notas-funções (contém quatro aspectos):

- 2M1a -- informa a distribuição das notas diatônicas em cada *corpus*, considerando os modos maior e menor. Não há hipóteses previamente associadas a este atributo.   

- 2M1b -- informa a distribuição das inflexões melódicas em relação às notas-estruturais. Não há hipóteses previamente associadas a este atributo.    

- 2M1c -- compara as distribuições das superclasses de notas-estruturais (básicas $\times$ tensões). Por hipótese, a presença significativa de tensões é um forte marcador centrípeto para os subconjuntos MPB e JAZZ.

- 2M1d -- detalha o atributo 2M1c, considerando as classes de notas-estruturais (tríade, tétrade, tensões simples e tensões alteradas). Por hipótese, melodias do subconjunto-alvo apoiam-se, em média, mais em tensões do que aquelas provenientes do subconjunto JAZZ e, significativamente, mais ainda do que as do superconjunto.

---

**2M2** -- nível das alturas (contém dois aspectos):

- 2M2a -- compara as distribuições das classes básicas de c-letras (u, P/p, A/a, S/s) em cada *corpus*. Não há hipóteses previamente associadas a este atributo. 

- 2M2b -- detalha o atributo 2M2a, comparando as distribuições das c-letras em cada *corpus*. Não há hipóteses previamente associadas a este atributo.   

---

**2M3** -- nível do ritmo (contém três aspectos):

- 2M3a -- compara as distribuições dos perfis métricos dos *corpora*. Por hipótese, membros do subconjunto-alvo (especialmente aqueles que apresentam, em maior ou menor medida, influências do gênero SAMBA) se diferenciarão dos membros do subconjunto JAZZ por ocorrências de ataques mais significativa nos pontos 4 e 10.

- 2M3b -- informa as distribuições de r-letras *contramétricas* (c, e, g, m, n, p, u) em cada *corpus*, incluindo sua presença percentual em relação ao todo das r-letras. Por hipótese, membros do subconjunto-alvo (especialmente aqueles que apresentam, em maior ou menor medida, influências do gênero SAMBA) se diferenciarão dos membros do subconjunto JAZZ pela massiva ococrrência de r-letras contramétricas.  

- 2M3c -- informa as distribuições de r-letras "tercinais" (d, f, i, k, o, s) em cada *corpus*, incluindo sua presença percentual em relação ao todo das r-letras. Não há hipóteses previamente associadas a este atributo.    
