---
title: Léxico de categorias funcionais
---

### Classe "Diatônicas" (DIA) / Subclasses "Primárias" (PRI) e "Secundárias" (SEC)

| Subclasse | categoria | Dó maior | Dó menor |
|-----------|-----------|----------|----------|
| PRI       | I         | CM7      | Cm7      |
|           | IV        | FM7      | Fm7      |
|           | V         | G7       | G7       |
| SEC       | II        | Dm7      | D∅       |
|           | III       | Em7      | EbM7     |
|           | VI        | Am7      | AbM7     |
|           | VII       | B∅       | B°       |


### Classe "Preparatórias" (PRE) / Subclasses "Dominantes secundárias" (DS), "Substitutos tritônicos" (SUBV) e "Diminutos" (DIM)

| Subclasse | categoria | Dó maior | Dó menor |
|-----------|-----------|----------|----------|
| DS        | V/II      | A7       | A7       |
|           | V/III     | B7       | Bb7      |
|           | V/IV      | C7       | C7       |
|           | V/V       | D7       | D7       |
|           | V/VI      | E7       | Eb7      |
|           | V/VI      | -        | F7       |
| SUBV      | SubV      | Db7      | Db7      |
|           | SubV/II   | Eb7      | Eb7      |
|           | SubV/III  | F7       | Fb7      |
|           | SubV/VI   | Gb7      | Gb7      |
|           | SubV/V    | Ab7      | Ab7      |
|           | SubV/VI   | Bb7      | A7       |
|           | SubV/VII  | -        | B7       |
| DIM       | V°        | B7       | B7       |
|           | V°/II     | C#°      | C#°      |
|           | V°/III    | D#°      | D°       |
|           | V°/IV     | E°       | E°       |
|           | V°/V      | F#°      | F#°      |
|           | V°/VI     | G#°      | G°       |
|           | V°/VII    | -        | A7       |
|           | I°        | C°       | -        |
|           | bIII°     | Eb°      | -        |
|           | IV°       | F°       | -        |
|           | V°        | G°       | -        |
|           | bVII°     | Bb°      | -        |


### Classe "Empréstimos de primeira ordem" (E1) / Subclasses "Regiões afins" (RA), "Empréstimos diatônicos" (ED) e "Subdominantes menores" (sd)

| Subclasse | categoria | Dó maior | Dó menor |
|-----------|-----------|----------|----------|
| RA        | Im7       | Cm7      | -        |
|           | bIIIM7    | EbM7     | -        |
|           | IV7       | F7       | F7       |
|           | bIIIM7    | EbM7     | -        |
|           | Vm7       | Gm7      | Gm7      |
|           | bVIIM7    | BbM7     | -        |
| ED        | IIm7      | -        | Dm7      |
|           | III(#5)M7 | -        | Eb(#5)M7 |
|           | #VI∅      | -        | A∅       |
| sd        | bIIM7     | DbM7     | DbM7     |
|           | II        | D        | -        |
|           | IVm7      | Fm7      | -        |
|           | bVIM7     | AbM7     | -        |
|           | bVII7}    | Bb7      | Bb7      |

### Classe "Napolitanos secundários" (NPS) 

| categoria | Dó maior | Dó menor |
|-----------|----------|----------|
| Np/II     | EbM7     | EbM7     |
| Np/III    | FM7      | FbM7     |
| Np/IV     | GbM7     | GbM7     |
| Np/V      | AbM7     | AbM7     |
| Np/VI     | BbM7     | AM7      |

### Classe "Anti-preparatórias" (aPRE) / Subclasses "Anti-Napolitanos" (aNP) e "Anti-Substitutos tritônicos" (aSUBV) 

| Subclasse | categoria | Dó maior | Dó menor |
|-----------|-----------|----------|----------|
| aNP       | aNp       | BM7      | BM7      |
|           | aNp/II    | C#M7     | C#M7     |
|           | aNp/III   | D#M7     | DM7      |
|           | aNp/IV    | EM7      | EM7      |
|           | aNp/V     | F#M7     | F#M7     |
|           | aNp/VI    | G#M7     | GM7      |
| aSUBV     | aSubV     | B7       | B7       |
|           | aSubV/II  | C#7      | C#7      |
|           | aSubV/III | D#7      | D7       |
|           | aSubV/IV  | E7       | E7       |
|           | aSubV/V   | F#7      | F#7      |
|           | aSubV/VI  | G#7      | G7       |

### Classe "Dominantes terciários" (DT) 

| categoria | Dó maior | Dó menor |
|-----------|----------|----------|
| V/bII     | Ab7      | Ab7      |
| V/bIII    | Bb7      | -        |
| V/bVI     | Eb7      | -        |
| V/bVII    | F7       | -        |

### Classe "Empréstimos de segunda ordem" (E2) 

| categoria       | Dó maior | Dó menor |
|-----------------|----------|----------|
| bIIm7           | Dbm7     | -        |
| bIIIm7 (≡ IIIm7)| Ebm7     | Ebm7     |
| bVIm7 (≡ VIm7)  | Abm7     | Abm7     |
| bVIIm7          | Bbm7     | Bbm7     |
| IIIM7           | EM7      | -        |
| bVM7            | GbM7     | GbM7     |
| VIM7            | AM7      | -        |
| VIIM7           | BM7      | -        |

