---
title: Glossário
---

**Alfabetos** --  conjuntos formados por **c/r letras**. No caso do subdomínio das alturas, o conjunto é denotado por Ac, tendo por membros as sete c-letras: A, a, P, p, S, s, u. Já o alfabeto rítmico, denotado por Ar, é formado por 26 r-letras: a, b, c, d, ..., x, y, z.

**Antinapolitanos** (aNp) -- **subclasse de categoria funcional** (membro da classe aPRE) formada por acordes napolitanos com "polaridade invertida", ou seja, resolvem em alvos com fundamentais posicionadas um semitom acima, em vez de um semitom abaixo.

**Anti-SubV** (aSubV) -- **subclasse de categoria funcional** (membro da classe aPRE) formada por acordes SubV com "polaridade invertida", ou seja, resolvem em alvos com fundamentais posicionadas um semitom acima, em vez de um semitom abaixo.

**c/r letra** -- unidade considerada no modelo de **Filtragem Melódica**. Podem ser associadas aos subdomínios das alturas (prefixo "c") ou dos ritmos (prefixo "r"). As c/r letras compõem **alfabetos** específicos.

**c/r palavra** -- estrutura resultante da concatenação de **c/r letras**, a partir da codificação em símbolos (de acordo com as convenções do modelo de **Filtragem Melódica** de trechos melódicos previamente segmentados.

**c/r sentença** -- estrutura resultante da concatenação de **c/r palavras**. Uma c/r sentença corresponde à transcrição de uma melodia em análise nos termos do modelo de **Filtragem Melódica**.

**Categorias funcionais** -- identificação lexical da propriedade funcional de um determinado acorde contextualizado em um campo tonal (por exemplo: I, III, V/VI, SubV/IV, IVm7 etc.).

**Classes e subclasses funcionais** -- conjuntos que abarcam **categorias funcionais** afins. No contexto do projeto, existem sete classes (que contêm, eventualmente, subclasses): (1) Diatônica (DIA) -- Principais (PRI) e Secundárias (SEC); (2) Preparatórias (PRE) -- Dominantes secundárias (DS), Locuções (LOC), Substitutas tritônicas (SUB), Diminutas (DIM); (3) Empréstimos de primeira ordem (E1) -- Regiões afins (RA), Subdominantes menores (sd); (4) Napolitanas secundárias (NPS); (5) Antipreparatórias (aPRE) -- Anti-subVs (aSUB), Antinapolitanas (aNP); (6) Dominantes terciárias (DT); (7) Empréstimos de segunda ordem (E2).

**Classes de notas-funções** -- conjuntos que agregam as **notas-funções** de acordo com suas relações com os acordes que as harmonizam. São as seguintes: Inflexões; Básicas (notas-funções 1, 3 e 5); Tetrádicas (6 e 7); Tensões simples (9, 11, 13 e 14); Tensões alteradas (b9, #9, #11 e b13).

**Classes de regiões tonais** -- englobam regiões tonais por graus de maior ou menor afinidades (não necessariamente proporcionais às suas mútuas proximidades). São elas: (1) Vizinhas (VIZ); (2) Vizinho-relativas (R/VIZ); (3) Mediânticas cromárticas (MED); (4) Medinte-relativas (R/MED); (5) Adjacentes (ADJ); (6) Cromáticas (CRO) e (7) Tritonais. Por sua vez, as classes podem ser agrupadas em dois superconjuntos, o das relações Notáveis (classes 1, 2 e 4) e o das demais relações (classes 3, 5, 6 e 7). A ideia de classe é intimamente associada ao conceito de **relações binárias tonais**.

**Coeficiente de afinidade acordal** (c) -- valor real (entre 0 e 1) correspondendo ao grau de semelhança entre dois tipos acordais} que integram uma **relação binária**. É calculado como a razão entre o dobro do número de classes de alturas em comum entre os dois acordes e a soma de suas cardinalidades.

**Divisor métrico** -- no contexto do modelo de **Filtragem Melódica**, é o número que divide a unidade temporal, de modo a formar uma **grade micrométrica** adequada para um determinado repertório de análise. No caso presente, adota-se o divisor 12. Ver também o tópico **subdivisor métrico**.

**Empréstimos de segunda ordem** (E2) -- **classe de categoria funcional**  formada por acordes que podem ser considerados como empréstimos modais (no sentido proposto pela teoria convencional) de empréstimos convencionais (ou seja, da **classe E1**). Por exemplo, a categoria bVIIm7 seria, por essa lógica, empréstimo do empréstimo IVm7 (=IVm7/IVm7).

**Entropia** -- conceito originado da Teoria da Informação, representa uma medida da incerteza de um determinado evento, considerando suas possíveis continuações. A entropia é quantificada em bits.

**Filtragem Melódica** -- processo de conversão de uma melodia, adotado no modelo homônimo, com o intuito de gerar classes de padrões de alturas e de ritmo para subsequente análise comparativa. A filtragem de uma melodia é realizada a partir de três fases sequenciais e complementares: segmentação, abstração e codificação.

**Genera de Tipos Acordais** -- conjuntos formados por **protoacordes** e suas variantes, reunidos por afinidades construtivas. São 10 os genera considerados, nomeados com as letras finais do alfabeto latino, em ordem inversa: Z ("maior com sétima maior"), Y ("dominante"), W ("sexta francesa"), X ("dominante aumentado"), V ("tríade maior"), z ("menor com sétima"), y ("meio-diminuto"), x ("diminuto"), w ("menor com sétima maior"), v ("tríade menor").

**Genus** (plural *genera*) -- conjunto que agrega um **protoacorde** e todos os possíveis **tipos acordais** derivados por meio de aplicação de transformações, dentro do modelo teórico dos **Genera de Tipos Acordais**. O modelo considera dez *genera* que reunem 161 protoacordes e variantes, formando o **léxico de tipos acordais** adotado no sistema.

**Grade micrométrica** -- estrutura abstrata resultante da divisão de um tempo (semínima) por um **divisor métrico**, sobre a qual são estabelecidas as **r-letras**. No projeto, a grade micrométrica é segmentada em 12 posições, o que permite a criação de um **alfabeto** rítmico com 26 componentes.

**Índice de ancoragem** (ia) -- métrica que busca avaliar o nível de complexidade entre uma determinada **nota-função** e o acorde que a harmoniza. É expresso como um valor entre 0 (complexidade mínima ou ancoragem máxima) e 1 (complexidade máxima ou ancoragem mínima). 

**Índice de contrametricidade** (ic) -- valor real (entre 0 e 1) que busca estabelecer uma medida para a contrametricidade [@sandroni-feitiço] de dada **r-palavra**, sendo calculado algoritmicamente.

**Índice de economia intervalar** (iE) -- métrica que busca avaliar o perfil de contornos de uma **c-palavra** de acordo com a maior ou menor ocorrência de movimentos intervalares «econômicos». As **c-letras** se dividem, quanto ao grau de economia intervalar, em quatro categorias: máxima (u), alta (P, p), média (A, a) e baixa (S, s). O iE é expresso como um número real entre 0 e 1.

**Índice de economia intervalar compensada** (iEc) -- versão complementar do **índice de economia intervalar**, que leva em conta as direções das **c-letras** na avaliação das **c-palavras**.  O iEc é expresso como um número real entre 0 e 1.

**Inter-onset intervals** (IOI) -- ou "intervalos entre ataques", em uma tradução livre do original inglês. Refere-se a classes de sequências rítmicas que são equivalentes pelas posições métricas de suas articulações, independentemente das durações de som ou silêncio entre elas.

**Léxico de tipos acordais** -- lista com os  161 **tipos acordais** considerados neste projeto, envolvendo **protoacordes** e suas variantes disponíveis. 

**Locução dominante** -- uma das possíveis denominações para fórmulas cadenciais que se caracterizam pelo desdobramento do acorde dominante (V) em uma **relação binária funcional** II|V, mantendo a função original. Pode ser primária (quando o V é o dominante primário, diatônico) ou secundária (no caso de dominantes secundários, V/II, V/III etc.). A fórmula integra a **subclasse funcional** LOC, dentro da classe PRE.

**Nota-função** -- refere-se a uma nota contextualizada em um determinado acorde. Uma nota-função expressa não a classe de altura a que está associada (Mi, Dó$\sharp$ etc.), mas a função que exerce no acorde que a contém: fundamental, terça, sexta, nona menor etc. 

**Notação genealógica** -- representação descritiva de um **tipo acordal** de modo a evidenciar sua origem como **protoacorde** ou variante em relação a um determinado **genus**.

**Perfil métrico** -- gráfico de barras usado para apresentação da distribuição dos ataques rítmicos correspondentes à **grade micrométrica** referente a uma peça ou repertório analisado no projeto.

**Protoacorde** -- **tipo acordal** básico associado a um **genus**. Existem dez protoacordes no modelo GTA, identificados pelas letras do genus com um zero em subscrito: "maior com sétima maior" (Z0 = CM7), "dominante" (Y0 = C7), "sexta francesa" (X0 = C(b5)7), "dominante aumentado" (W0 = C(#5)7), "tríade maior" (V0 = C), "menor com sétima menor" (z0 = Cm7), "meio diminuto" (y0 = Cm7(b5)), "sétima diminuta" (x0 = C°),  "menor com sétima maior" (w0 = Cm(M7)) e "tríade menor" (v0 = Cm).

**Regiões mediânticas cromáticas** -- denominação genérica atribuída às regiões tonais posicionadas a intervalos de terça (ascendente e descendente, maior e menor) da tônica referencial, excluindo-se aquelas regiões vizinhas (mediante e submediante), consideradas mediânticas diatônicas.

**Relação binária** (RB) -- relação funcional entre dois **tipos acordais** contíguos. Sua notação informa o intervalo entre as fundamentais dos dois TAs e suas qualidades, podendo ser representada em cifras ou, mais formalmente, em **notação genealógica**. É a mais específica das relações binárias e, portanto, a de menor potencial de generalização.

**Relação binária abstrata** (RBA) -- versão essencial de uma **relação binária** que considera apenas o intervalo entre as fundamentais e os respectivos **genera** de procedência dos **tipos acordais** que a formam.

**Relação binária funcional** (RBF) -- uma relação entre acordes contíguos que considera suas respectivas **categorias funcionais** (por exemplo, V|I).

**Relação binária funcional de alto nível** (RBFa) -- filtragem de uma **relação binária funcional** considerando apenas as **classes funcionais** que integram (por exemplo, DIA|DIA, PRE|DIA, DT|E1 etc.)

**Relação binária tonal** (RBF) -- relação entre tonalidades contíguas considerando apenas seus modos (maior ou menor) e a distância intervalar entre suas tônicas (por exemplo, M5m, significando relação entre uma tonalidade maior e uma menor distanciadas por cinco semitons, o que engloba diversas possibilidades, como Dó maior|Fá menor, Mi maior|Lá menor etc.)

**Subconjunto-alvo** -- designação eventual para o conjunto dos *corpora* MPB. Em mesmo nível se apresentam os repertórios de controle, também como subconjuntos: SAMBA, CHORO e JAZZ. O subconjunto-alvo (assim como os subconjuntos SAMBA e CHORO) mantém uma relação de pertencimento ao que é aqui denominado superconjunto da "música popular urbana do Brasil". Este, por sua vez e evidentemente, estaria inserido em conjuntos ainda mais abrangentes, como: "música popular urbana", "música tonal" etc.

**Subdivisor métrico** -- número que divide um **divisor métrico**. No contexto do projeto, são subdivisores os números 1, 2, 3, 4, 6 e 12, porém, na prática são considerados apenas 3 e 4.

**Teia de notas-funções** -- representação geométrica das relações entre notas melódicas e os acordes que as harmonizam. Seu nome deriva de seu formato, com cínco círculos concêntricos (correspondendo às **classes de notas-funções** considerados) cortados por 12 raios, representando graus escalares diatônicos e cromátic0s.

**Tipo acordal** (TA) -- configuração abstrata de um acorde, desconsiderando fundamental e notas específicas. Equivalente à ideia de qualidade acordal. Um TA pode ser representado como bloco ou sequência de intervalos (em formação compacta, dentro de uma oitava), em cifragem alfanumérica (com fundamental em Dó, por convenção) ou em **notação genealógica**. 

