---
title: Introdução
---

Diversificada, sofisticada, surpreendente e, principalmente, bela são adjetivos que podem ser atribuídos em termos gerais à música popular praticada no Brasil, em suas incontáveis expressões, compositores, gêneros e épocas. Trata-se de um patrimônio cultural de valor incalculável que não tem paralelos no planeta, uma enorme riqueza que traz aos brasileiros muito orgulho e carinho.

Isso posto, é natural -- e, claro, bastante oportuno -- que a música popular do Brasil seja tomada como um atraente e rico objeto de estudo. Especialmente nos tempos mais recentes, muitos trabalhos acadêmicos têm sido publicados com as mais diversas abordagens, não apenas sintonizadas a importantes questões contextuais, históricas, biográficas, estéticas, sociais, políticas, raciais, de gênero etc., mas também, claro, musicológicas e/ou etnomusicológicas, trazendo luzes cada vez mais abrangentes, precisas e detalhadas sobre esse fascinante tema.

Entretanto, considerando especificamente o escopo no qual se insere a presente iniciativa -- ou seja, dos estudos sistemáticos em música --, embora observe-se o despertar recente de um grande interesse acadêmico por temas associados, o quadro ainda é incipiente, se comparado à situação das demais abordagens. Este projeto tem, justamente, como principal motivação contribuir para diminuir essa lacuna. Associa-se a uma pesquisa de amplo âmbito, iniciada em 2017 e vinculada ao Programa de Pós-Graduação em Música da Universidade Federal do Rio de Janeiro, dentro da linha de pesquisa Poéticas da Criação Musical, subordinada à área de Processos Criativos.

Em termos mais específicos, este projeto tem um propósito bastante ambicioso, a saber, determinar de modo sistemático os contornos do contexto estético-musical que informalmente é denominado Música Popular Brasileira, mais conhecido pelo acrônimo MPB. O principal obstáculo dessa tarefa se apresenta já na clara definição do *que seria* de fato a MPB. Tendo nosso intuito um caráter primordialmente técnico, estrutural, não desejamos nos embrenhar a fundo em questões complexas (especialmente relacionadas a aspectos sociais, históricos e políticos) na busca de definições, mesmo porque não cremos que haja perfeito consenso na estrutura especializada sobre os limites históricos-estéticos da MPB. Entretanto, não podemos -- nem devemos -- ignorar aspectos extramusicais em nossa investigação, sob pena de realizarmos um estudo (na melhor das hipóteses) musicalmente "correto", porém frio, descontextualizado e desplugado dos acontecimentos e pensamentos que contribuíram em muito para moldar os rumos tomados pelos compositores e compositoras do período, cujos reflexos foram profundamentos esculpidos em suas respectivas obras.

Por outro lado, a MPB *não é*, de modo algum, para nós como um fóssil recentemente descoberto ou um objeto distante no espaço ou no tempo. Nós a vivemos, admiramos, amamos, a tornamos virtualmente parte importante de nossas vidas. Em outros termos, é possível dizer que nós, como coordenadores e pesquisadores desse projeto, na qualidade de habitantes e, por que não, atores do contexto em questão, sentimo-nos habilitados e qualificados para estudá-lo. Ainda que seja difícil definir com a devida precisão a essência e os limites temporais desse período para alguém que não teve a mesma vivência (digamos, uma adolescente roqueira, um amigo estrangeiro, por exemplo), de um modo geral, *sabemos* razoavelmente bem do que se trata quando conversamos ou ouvimos falar sobre o assunto. É, ao menos, um bom ponto de partida.

Mas, afinal, *o que é* a MPB? Podemos começar a examinar essa questão considerando o que ela *não* é. A MPB certamente não é um gênero musical, mas abarca uma enorme diversidade deles, por exemplo, samba, bossa-nova, afoxé, baião, bolero, xote, choro, rock, blues etc., etc. Mais relevante ainda, compositores da MPB não atuam exclusivamente em um determinado gênero, pelo contrário, a regra é que experimentem diversos deles em suas obras. Considere, como exemplo, a grande diversidade que existe nesse aspecto na música de Tom Jobim, Caetano Veloso e Gilberto Gil, entre muitos outros. Mesmo aqueles e aquelas que atuam mais caracteristicamente num nicho do espectro de gêneros (Rita Lee, Alceu Valença, Paulinho da Viola etc.), não compõem unicamente peças de seus gêneros preferenciais.

Consequentemente, a MPB também não é um estilo. Mais precisamente, ela resulta da combinação de um formidável número de preferências estilísticas pessoais/composicionais que apresentam tanto características idiossincráticas quanto notáveis pontos de contato entre si. Determinar de maneira precisa e sistemática esses elementos corresponde exatamente ao cerne deste projeto. Em outros termos, nosso propósito é investigar profundamente o que denominaremos a *Prática Comum da MPB*.[^1] Tal investigação tem como base um sólido e complexo aparato teórico-metodológico, elaborado, desenvolvido e aperfeiçoado em estágios precedentes da pesquisa, que podem ser sucintamente descritos como se segue:[^2]

[^1]: O termo mantém uma relação de analogia com o conceito conhecido como Prática Comum (*Common Practice*), associado ao período composicional no qual a tonalidade foi o elemento invariante na criação musical, a despeito das diferenças específicas entre compositores e épocas, considerando um arco temporal de aproximadamente 300 anos, 1600-1900. Recentemente, @tymoczko-geometry propôs a ideia de uma Prática Comum Estendida (*Extended Common Practice*), abarcando tanto obras renascentistas quanto aquelas pós-tonais e mesmo parte da música popular (especialmente, o jazz e o rock).

[^2]: As etapas iniciais contaram com a ajuda de uma excelente equipe de estudantes, graduandos e pós-graduandos da Escola de Música da UFRJ (em ordem alfabética): Ana Miccolis, Claudia Usai, Eduardo Cabral, Gabriel Barbosa, João Penchel, Igor Chagas, Max Kühn e Vinicius Braga. Atualmente, o grupo conta com a participação de Matheus Forli, como bolsista de Iniciação Científica.

* **Fase 1** -- realizada entre 2017 e 2018, tendo como objeto de estudo a estrutura harmônica do cancioneiro de Antonio Carlos Jobim, englobando 145 obras. **Objetivos:** mapear as estruturas dos acordes empregados (ou seja, suas qualidades) e as relações entre duplas de acordes contíguos. **Limitações:** (1) relações funcionais e entre tonalidades (ou seja, a funcionalidade de médio e alto níveis) não foram contempladas pela análise; (2) o sistema de análise era capacitado a reconhecer apenas 10 qualidades acordais básicas,[^3] desconsiderando nuances importantes e bem recorrentes no repertório, como sextas, quartas suspensas, bem como a adição de qualquer tipo de tensão harmônica.

[^3]: Mais precisamente, os 10 *genera* atualmente considerados na pesquisa. Esse tópico será descrito em detalhes oportunamente (ver também o Glossário de termos).

* **Fase 2** -- realizada entre 2018 e 2019, cobrindo o mesmo repertório e tendo os mesmos objetivos da Fase 1. Na verdade, consistiu basicamente na reaplicação do processo analítico anterior a partir de um importante aperfeiçoamento que capacitou o sistema a reconhecer qualquer qualidade acordal empregada pelo compositor em suas canções, eliminando uma das fragilidades da pesquisa. **Limitação:** o sistema manteve-se apto para analisar apenas as relações de baixo nível, ou seja, entre acordes contíguos, não levando em conta as organizações funcionais e tonais das peças em análise.

* **Fase 3** -- realizada entre 2021 e 2022, consolidando as etapas anteriores e incorporando importantes aperfeiçoamentos: (1) abordagens analíticas harmônicas contemplando as organizações funcional (nível médio) e tonal (nível alto) das peças analisadas e (2) a ampliação do processo analítico de modo a englobar também o mapeamento da dimensão melódica, subdividida em alturas e ritmo.[^4] A estrutura e os principais resultados da pesquisa dessa fase foram documentados em dois livros voltados para as construções harmônica e melódica de Jobim [@almada-harmonia-jobim; @almada-melodia-jobim].

[^4]: O que é regido pelo modelo teórico da Filtragem Melódica, a ser oportunamente descrito.

* **Fase 4** -- iniciada em 2022 e em andamento, trata-se justamente do presente projeto. Tem como meta a aplicação da tecnologia teórico-metodológica desenvolvida na Fase 3 (focada na música de Jobim) no estudo de um grupo de 10 compositores de reconhecida atuação no cenário musical brasileiro, de modo a iniciar uma investigação sistemática sobre uma possível fundamentação de uma Prática Comum da MPB, bem como, possivelmente, identificar características estilísticas individuais desses compositores. Além dos anteriores, novos modelos teóricos (acompanhados das respectivas ferramentas analíticas) foram elaborados, de modo a tornar o processo analítico mais acurado e abrangente. Tais modelos e métodos serão minuciosamente comentados e descritos em capítulos posteriores.
