---
title: "Listagem dos *corpora*"
---

## MPB

### Tom Jobim

[Site oficial](https://www.jobim.org/)

[Playlist](https://open.spotify.com/playlist/7HDlN5BRxsGnOwp0NVLBGt)

1. *Absolute Lee* (Antonio Carlos Jobim)
1. *Água de beber* (Antonio Carlos Jobim e Vinicius de Moraes)
1. *Ai quem me dera* (Antonio Carlos Jobim  e Marino Pinto)    
1. *Angela* (Antonio Carlos Jobim)        
1. *Bebel* (Antonio Carlos Jobim)     
1. *Bonita* (Antonio Carlos Jobim, Gene Lees e Ray Gilberto Gilbert)        
1. *Brigas nunca mais* (Antonio Carlos Jobim e Vinicius de Moraes)
1. *Caminho de pedra* (Antonio Carlos Jobim e Vinicius de Moraes)
1. *Caminhos cruzados* (Antonio Carlos Jobim e Newton Mendonça)   
1. *Canção do amor demais* (Antonio Carlos Jobim e Vinicius de Moraes)
1. *Chega de saudade* (Antonio Carlos Jobim e Vinicius de Moraes)
1. *Corcovado* (Antonio Carlos Jobim)  
1. *Demais* (Antonio Carlos Jobim e Aloysio de Oliveira) 
1. *Derradeira primavera* (Antonio Carlos Jobim e Vinicius de Moraes)   
1. *Desafinado* (Antonio Carlos Jobim e Newton Mendonça)   
1. *Dindi* (Antonio Carlos Jobim e Aloysio de Oliveira)     
1. *Discussão* (Antonio Carlos Jobim e Newton Mendonça)  
1. *É preciso dizer adeus* (Antonio Carlos Jobim e Vinicius de Moraes) 
1. *Ela é carioca* (Antonio Carlos Jobim e Vinicius de Moraes)      
1. *Engano* (Antonio Carlos Jobim e Newton Mendonça e Luis Bonfá)   
1. *Este seu olhar* (Antonio Carlos Jobim) 
1. *Estrada do sol* (Antonio Carlos Jobim e Dolores Duran)    
1. *Eu e o meu amor* (Antonio Carlos Jobim e Vinicius de Moraes)    
1. *Eu sei que vou te amar* (Antonio Carlos Jobim e Vinicius de Moraes)   
1. *Faz uma semana* (Antonio Carlos Jobim e João Stockler)      
1. *Garota de Ipanema* (Antonio Carlos Jobim e Vinicius de Moraes)   
1. *Incerteza* (Antonio Carlos Jobim e Newton Mendonça) 
1. *Insensatez* (Antonio Carlos Jobim e Vinicius de Moraes)   
1. *Janelas abertas* (Antonio Carlos Jobim e Vinicius de Moraes)      
1. *Lamento no morro* (Antonio Carlos Jobim e Vinicius de Moraes)       
1. *Ligia* (Antonio Carlos Jobim)  
1. *Luar e batucada* (Antonio Carlos Jobim)  
1. *Luiza* (Antonio Carlos Jobim e Newton Mendonça)       
1. *Mágoa* (Antonio Carlos Jobim e Marino Pinto)  
1. *Meditação* (Antonio Carlos Jobim e Newton Mendonça)  
1. *Modinha* (Antonio Carlos Jobim e Vinicius de Moraes)  
1. *O amor em paz* (Antonio Carlos Jobim e Vinicius de Moraes)  
1. *Pois é* (Antonio Carlos Jobim e Chico Buarque)  
1. *Sabiá* (Antonio Carlos Jobim e Chico Buarque)  
1. *Samba de uma nota só* (Antonio Carlos Jobim e Newton Mendonça)  
1. *Samba do avião* (Antonio Carlos Jobim)  
1. *Se todos fossem iguais a você* (Antonio Carlos Jobim e Vinicius de Moraes)  
1. *Só danço samba* (Antonio Carlos Jobim e Vinicius de Moraes)  
1. *Só tinha de ser com você* (Antonio Carlos Jobim e Aloysio de Oliveira)  
1. *Solidão* (Antonio Carlos Jobim e Alcides Fernandes)  
1. *Tereza da praia* (Antonio Carlos Jobim e Billy Blanco)  
1. *Triste* (Antonio Carlos Jobim)  
1. *Vivo sonhando* (Antonio Carlos Jobim)  
1. *Você vai ver* (Antonio Carlos Jobim)        
1. *Wave* (Antonio Carlos Jobim)  

### Ivan Lins

[Site oficial](https://ivanlins.com.br/)

[Playlist](https://open.spotify.com/playlist/5bewWfR5wUDizEZVUJcBQa)

1. *Abre alas* (Ivan Lins e Vitor Martins)  
1. *Acaso* (Ivan Lins e Abel Silva)        
1. *A cor do pôr-do-sol* (Ivan Lins e Celso Viáfora)  
1. *Agora* (Ivan Lins e Ronaldo Monteiro de Souza)    
1. *Ai, ai, ai, ai, ai, ai* (Ivan Lins e Vitor Martins)      
1. *Ainda te procuro* (Ivan Lins e Vitor Martins)      
1. *A noite* (Ivan Lins e Vitor Martins)      
1. *Amor* (Ivan Lins e Vitor Martins)  
1. *Anjo de mim* (Ivan Lins e Vitor Martins)  
1. *Aos nossos filhos* (Ivan Lins e Vitor Martins)    
1. *Aparecida* (Ivan Lins e Maurício Tapajós)       
1. *Arlequim desconhecido* (Ivan Lins e Vitor Martins)  
1. *Bandeira do Divino* (Ivan Lins e Vitor Martins)  
1. *Bilhete* (Ivan Lins e Vitor Martins)  
1. *Bonito* (Ivan Lins e Vitor Martins)  
1. *Camaleão* (Ivan Lins, Vitor Martins e Aldir Blanc)      
1. *Cantor da noite* (Ivan Lins e Vitor Martins)  
1. *Cartomante* (Ivan Lins e Vitor Martins)       
1. *Choro das águas* (Ivan Lins e Vitor Martins)  
1. *Coragem mulher* (Ivan Lins e Vitor Martins)       
1. *Daquilo que eu sei* (Ivan Lins e Vitor Martins)  
1. *Depois dos temporais* (Ivan Lins)  
1. *Dinorah, Dinorah* (Ivan Lins e Vitor Martins)  
1. *Doce presença* (Ivan Lins e Vitor Martins)  
1. *Essa maré* (Ivan Lins e Ronaldo Monteiro de Souza)  
1. *Fogueira* (Ivan Lins e Vitor Martins)  
1. *Guarde nos olhos* (Ivan Lins e Vitor Martins)  
1. *Iluminados* (Ivan Lins e Vitor Martins)  
1. *Ituverava* (Ivan Lins e Vitor Martins)       
1. *Joana dos barcos* (Ivan Lins e Vitor Martins)  
1. *Lembra* (Ivan Lins e Vitor Martins)      
1. *Lembra de mim* (Ivan Lins e Vitor Martins)  
1. *Leva e traz (Elis)* (Ivan Lins e Vitor Martins)  
1. *Madalena* (Ivan Lins e Ronaldo Monteiro de Souza)  
1. *Meu país* (Ivan Lins e Vitor Martins)    
1. *Mudança dos ventos* (Ivan Lins e Vitor Martins)    
1. *Na areia, na beira do mar* (Ivan Lins e Cláudio Jorge)    
1. *Novo tempo* (Ivan Lins e Vitor Martins)    
1. *O amor é meu país* (Ivan Lins e Ronaldo Monteiro de Souza)    
1. *Porta entreaberta* (Ivan Lins e Paulo César Pinheiro)   
1. *Quadras de roda* (Ivan Lins e Vitor Martins)  
1. *Rio de maio* (Ivan Lins e Celso Viáfora)  
1. *Saindo de mim* (Ivan Lins e Vitor Martins)  
1. *Sertaneja* (Ivan Lins e Vitor Martins)   
1. *Soberana rosa* (Ivan Lins e Vitor Martins)  
1. *Tens* (Ivan Lins e Ronaldo Monteiro de Souza)      
1. *Um fado* (Ivan Lins e Vitor Martins)  
1. *Velas içadas* (Ivan Lins e Vitor Martins)  
1. *Vitoriosa* (Ivan Lins e Vitor Martins)  
1. *Antes que seja tarde* (Ivan Lins e Vitor Martins)     

### Chico Buarque

[Site oficial](http://www.chicobuarque.com.br/)

[Playlist](https://open.spotify.com/playlist/0BifNmWohJVSSl0HgMnbGk)

1. *A banda* (Chico Buarque) 
1. *Acorda amor* (Chico Buarque e Leonel Paiva) 
1. *Agora falando sério* (Chico Buarque) 
1. *Apesar de você* (Chico Buarque)   
1. *A Rita* (Chico Buarque)           
1. *Atrás da porta* (Chico Buarque e Francis Hime) 
1. *Bastidores* (Chico Buarque)     
1. *Biscate* (Chico Buarque)             
1. *Bye bye Brasil* (Chico Buarque e Roberto Menescal) 
1. *Cálice* (Chico Buarque e Gilberto Gil)   
1. *Carolina* (Chico Buarque) 
1. *Com açúcar e com afeto* (Chico Buarque) 
1. *Construção* (Chico Buarque) 
1. *Cotidiano* (Chico Buarque) 
1. *Desalento* (Chico Buarque) 
1. *Desencontro* (Chico Buarque e Vinicius de Moraes) 
1. *Deixe a menina* (Chico Buarque)      
1. *De todas as maneiras* (Chico Buarque)    
1. *De volta ao samba* (Chico Buarque)     
1. *Ela desatinou* (Chico Buarque) 
1. *Fado tropical* (Chico Buarque e Ruy Guerra)   
1. *Feijoada completa* (Chico Buarque) 
1. *Flor da idade* (Chico Buarque) 
1. *Folhetim* (Chico Buarque)  
1. *Futuros amantes* (Chico Buarque)       
1. *Homenagem ao malandro* (Chico Buarque) 
1. *Januária* (Chico Buarque) 
1. *Joana francesa* (Chico Buarque) 
1. *Mambembe* (Chico Buarque)      
1. *Maninha* (Chico Buarque) 
1. *Meu caro amigo* (Chico Buarque) 
1. *Morena dos olhos d'água* (Chico Buarque)  
1. *Mulheres de Atenas* (Chico Buarque e Augusto Boal) 
1. *Não existe pecado ao sul do equador* (Chico Buarque e Ruy Guerra) 
1. *Noite dos mascarados* (Chico Buarque) 
1. *Olê olá* (Chico Buarque) 
1. *Olhos nos olhos* (Chico Buarque) 
1. *O meu amor* (Chico Buarque)            
1. *Paratodos* (Chico Buarque) 
1. *Pedro pedreiro* (Chico Buarque) 
1. *Pelas tabelas* (Chico Buarque) 
1. *Quem te viu, quem te vê* (Chico Buarque) 
1. *Roda viva* (Chico Buarque) 
1. *Samba de Orly* (Chico Buarque, Vinicius de Moraes e Toquinho)     
1. *Samba do grande amor* (Chico Buarque) 
1. *Samba e amor* (Chico Buarque)        
1. *Sem fantasia* (Chico Buarque) 
1. *Sob medida* (Chico Buarque)        
1. *Tatuagem* (Chico Buarque e Ruy Guerra)   
1. *Vai trabalhar vagabundo* (Chico Buarque)     

### Edu Lobo

[Site oficial](http://edulobo.com.br/)

[Playlist](https://open.spotify.com/playlist/0nvyNKHMzHy83HRIwZymQr)

1. *Abandono* (Edu Lobo e Chico Buarque)   
1. *Acalanto* (Edu Lobo e Chico Buarque)   
1. *Aguaverde* (Edu Lobo)             
1. *A história de Lilly Braun* (Edu Lobo e Chico Buarque)    
1. *Arrastão* (Edu Lobo e Vinicius de Moraes)   
1. *Arpoador* (Edu Lobo)   
1. *As mesmas histórias* (Edu Lobo)      
1. *Ave rara* (Edu Lobo e Aldir Blanc)   
1. *Beatriz* (Edu Lobo e Chico Buarque)        
1. *Borandá* (Edu Lobo)   
1. *Branca Dias* (Edu Lobo e Cacaso)   
1. *Candeias* (Edu Lobo)   
1. *Canção da terra* (Edu Lobo)         
1. *Casa forte* (Edu Lobo)   
1. *Canudos* (Edu Lobo e Cacaso)  
1. *Canto triste* (Edu Lobo e Vinicius de Moraes)   
1. *Chegança* (Edu Lobo e Oduvaldo Viana Filho)   
1. *Choro bandido* (Edu Lobo e Chico Buarque) 
1. *Cidade Nova* (Edu Lobo e Ronaldo Bastos)   
1. *Considerando* (Edu Lobo e Capinan)   
1. *Corrida de jangada* (Edu Lobo e Capinan) 
1. *Corrupião* (Edu Lobo)        
1. *Descompassado* (Edu Lobo e Cacaso)   
1. *Dono do lugar* (Edu Lobo e Cacaso) 
1. *Dos navegantes* (Edu Lobo e Paulo César Pinheiro) 
1. *Frevo diabo* (Edu Lobo e Chico Buarque) 
1. *Lero-lero* (Edu Lobo e Cacaso) 
1. *Meia-noite* (Edu Lobo e Chico Buarque)     
1. *Memórias de Marta Saré* (Edu Lobo e Gianfrancesco Guarnieri)   
1. *Meu namorado* (Edu Lobo e Chico Buarque)    
1. *Meus pensamentos de mágoa* (Edu Lobo, sobre um poema de Fernando Pessoa)   
1. *Na carreira* (Edu Lobo e Chico Buarque)    
1. *Na ilha de Lia, no barco de Rosa* (Edu Lobo e Chico Buarque)
1. *No cordão da saideira* (Edu Lobo)      
1. *O sertão* (Edu Lobo)       
1. *Pra você que chora* (Edu Lobo e Gianfrancesco Guarnieri)   
1. *Perambulando* (Edu Lobo)  
1. *Pianinho* (Edu Lobo e Aldir Blanc)         
1. *Ponteio* (Edu Lobo e Capinan)   
1. *Pra dizer adeus* (Edu Lobo e Torquato Neto)        
1. *Reza* (Edu Lobo e Ruy Guerra)     
1. *Senhora do Rio* (Edu Lobo)         
1. *Só me fez bem* (Edu Lobo e Vinicius de Moraes)       
1. *Sobre todas as coisas* (Edu Lobo e Chico Buarque)    
1. *Upa, neguinho* (Edu Lobo e Gianfrancesco Guarnieri)        
1. *Vento bravo* (Edu Lobo e Paulo César Pinheiro)    
1. *Viola fora de moda* (Edu Lobo e Capinan) 
1. *Zambi* (Edu Lobo e Vinicius de Moraes)        
1. *Zanga, zangada* (Edu Lobo e Ronaldo Bastos)  
1. *Zanzibar* (Edu Lobo)   

### Caetano Veloso

[Site oficial](https://www.caetanoveloso.com.br/)

[Playlist](https://open.spotify.com/playlist/7rIffYGLzaUnPM4dftNkPa)

1. *A filha da Chiquita Bacana* (Caetano Veloso)   
1. *Alegria, alegria* (Caetano Veloso)         
1. *A outra banda da Terra* (Caetano Veloso)   
1. *Atrás do trio elétrico* (Caetano Veloso) 
1. *Avarandado* (Caetano Veloso)       
1. *A tua presença morena* (Caetano Veloso)         
1. *Baby* (Caetano Veloso)   
1. *Beleza pura* (Caetano Veloso)       
1. *Cajuína* (Caetano Veloso) 
1. *Cavaleiro de Jorge* (Caetano Veloso)    
1. *Chuva, suor e cerveja* (Caetano Veloso)     
1. *Cinema Olímpia* (Caetano Veloso)         
1. *Como dois e dois* (Caetano Veloso)         
1. *Coração vagabundo* (Caetano Veloso)  
1. *Dom de iludir* (Caetano Veloso)          
1. *Drama* (Caetano Veloso) 
1. *Eclipse oculto* (Caetano Veloso) 
1. *Ele me deu um beijo na boca* (Caetano Veloso)    
1. *Esse cara* (Caetano Veloso)   
1. *Gema* (Caetano Veloso)      
1. *Gente* (Caetano Veloso) 
1. *Irene* (Caetano Veloso)       
1. *Jeito de corpo* (Caetano Veloso)   
1. *London, London* (Caetano Veloso)       
1. *Louco por você* (Caetano Veloso)      
1. *Lua de São Jorge* (Caetano Veloso)       
1. *Lua, lua, lua, lua* (Caetano Veloso)          
1. *Luz do sol* (Caetano Veloso)        
1. *Massa real* (Caetano Veloso)   
1. *Mel* (Caetano Veloso e Wally Salomão)       
1. *Menino do Rio* (Caetano Veloso) 
1. *Meu bem, meu mal* (Caetano Veloso)      
1. *Milagres do povo* (Caetano Veloso) 
1. *Minha voz, minha vida* (Caetano Veloso) 
1. *Muito* (Caetano Veloso)
1. *Não identificado* (Caetano Veloso)       
1. *No dia em que eu vim-me embora* (Caetano Veloso e Gilberto Gil)         
1. *Nosso estranho amor* (Caetano Veloso)  
1. *Odara* (Caetano Veloso)   
1. *O leãozinho* (Caetano Veloso)    
1. *O quereres* (Caetano Veloso) 
1. *Os argonautas* (Caetano Veloso) 
1. *Outras palavras* (Caetano Veloso) 
1. *Quero ir a Cuba* (Caetano Veloso) 
1. *Pecado original* (Caetano Veloso)     
1. *Podres poderes* (Caetano Veloso)     
1. *Rapte-me, camaleoa* (Caetano Veloso)   
1. *Sampa* (Caetano Veloso)     
1. *Sim, não* (Caetano Veloso e Bolão) 
1. *Superbacana* (Caetano Veloso) 

### Djavan

[Site oficial](https://djavan.com.br/)

[Playlist](https://open.spotify.com/playlist/4kKc4eHUMrOaWiGwsCj1uM)

1. *Açaí* (Djavan)  
1. *Água* (Djavan) 
1. *Alagoas* (Djavan)       
1. *Álibi* (Djavan)   
1. *Aquele um* (Djavan)         
1. *Asa* (Djavan)      
1. *Atitude* (Djavan)     
1. *Azul* (Djavan)    
1. *Beiral* (Djavan)  
1. *Capim* (Djavan)    
1. *Doidice* (Djavan)       
1. *Dupla traição* (Djavan)       
1. *E que Deus ajude* (Djavan)  
1. *Esfinge* (Djavan)        
1. *Estória de cantador* (Djavan)       
1. *Faltando um pedaço* (Djavan)
1. *Fato consumado* (Djavan)    
1. *Flor de lis* (Djavan)  
1. *Flor do medo* (Djavan)       
1. *Joaninha* (Djavan)       
1. *Lambada de serpente* (Djavan)         
1. *Lilás* (Djavan)  
1. *Luz* (Djavan)         
1. *Maçã* (Djavan)    
1. *Mal de mim* (Djavan)        
1. *Meu* (Djavan)     
1. *Meu bem querer* (Djavan)         
1. *Muito obrigado* (Djavan) 
1. *Nem um dia* (Djavan)    
1. *Nereci* (Djavan)  
1. *Nobreza* (Djavan)        
1. *Numa esquina de Hanói* (Djavan)       
1. *Obi* (Djavan)      
1. *Oceano* (Djavan)       
1. *Om* (Djavan)  
1. *Pétala* (Djavan)       
1. *Passou* (Djavan)  
1. *Pedro Brasil* (Djavan)       
1. *Que foi, my love?* (Djavan)       
1. *Samba dobrado* (Djavan)  
1. *Samurai* (Djavan)       
1. *Seduzir* (Djavan)     
1. *Serene* (Djavan)     
1. *Serrado* (Djavan)     
1. *Sílaba* (Djavan)        
1. *Sina* (Djavan)       
1. *Sururu de capote* (Djavan)   
1. *Tanta saudade* (Djavan e Chico Buarque)        
1. *Tem boi na linha* (Djavan)         
1. *Topázio* (Djavan)    

### João Bosco

[Site oficial](https://www.joaobosco.com.br/)

[Playlist](https://open.spotify.com/playlist/4UZMRJeXRtLMburXqLwVLy)

1. *Agnus sei* (João Bosco e Aldir Blanc)  
1. *A nível de...* (João Bosco e Aldir Blanc)         
1. *Bala com bala* (João Bosco e Aldir Blanc)   
1. *Beirando a rumba* (João Bosco e Francisco Bosco)     
1. *Bijuterias* (João Bosco e Aldir Blanc)     
1. *Boca de sapo* (João Bosco e Aldir Blanc)    
1. *Casa de marimbondo* (João Bosco e Aldir Blanc)       
1. *Corsário* (João Bosco e Aldir Blanc)         
1. *De frente pro crime* (João Bosco e Aldir Blanc)   
1. *Denúncia vazia* (João Bosco e Aldir Blanc)       
1. *Desenho de giz* (João Bosco e Abel Silva)       
1. *Dois pra lá, dois pra cá* (João Bosco e Aldir Blanc)       
1. *Escadas da Penha* (João Bosco e Aldir Blanc)    
1. *Falso brilhante* (João Bosco e Aldir Blanc)         
1. *Feminismo no Estácio* (João Bosco e Aldir Blanc)    
1. *Galos de briga* (João Bosco e Aldir Blanc)       
1. *Gol anulado* (João Bosco e Aldir Blanc)   
1. *Jade* (João Bosco) 
1. *Jandira da gandaia* (João Bosco e Aldir Blanc)     
1. *Jogador* (João Bosco e Aldir Blanc)        
1. *Kid Cavaquinho* (João Bosco e Aldir Blanc)   
1. *Latin lover* (João Bosco e Aldir Blanc)       
1. *Linha de passe* (João Bosco, Aldir Blanc e Paulo Emílio) 
1. *Meu caro visconde* (João Bosco e Aldir Blanc)          
1. *Miss suéter* (João Bosco e Aldir Blanc)     
1. *Nação* (João Bosco, Aldir Blanc e Paulo Emílio)
1. *Nesta data* (João Bosco e Aldir Blanc)      
1. *Nossas últimas viagens* (João Bosco, João Donato e Aldir Blanc)     
1. *O bêbado e a equilibrista* (João Bosco e Aldir Blanc)     
1. *O mestre-sala dos mares* (João Bosco e Aldir Blanc)      
1. *O rancho da goiabada* (João Bosco e Aldir Blanc)      
1. *Ofício de um puxador* (João Bosco e Aldir Blanc)    
1. *Papel machê* (João Bosco e Aldir Blanc)     
1. *Pirata azul* (João Bosco e Capinam)  
1. *Plataforma* (João Bosco e Aldir Blanc)     
1. *Preta-porter de tafetá* (João Bosco e Aldir Blanc)  
1. *Profissionalismo é isso aí* (João Bosco e Aldir Blanc)        
1. *Quando o amor acontece* (João Bosco e Aldir Blanc)       
1. *Querido diário* (João Bosco e Aldir Blanc)    
1. *Siameses* (João Bosco e Aldir Blanc)      
1. *Samba do pouso* (João Bosco e Vinicius de Moraes)    
1. *Siri recheado e o cacete* (João Bosco e Aldir Blanc)     
1. *Tabelas* (João Bosco e Aldir Blanc)           
1. *Tenho dito* (João Bosco)     
1. *Terra dourada* (João Bosco) 
1. *Tiro de misericórdia* (João Bosco e Aldir Blanc)       
1. *Trilha sonora* (João Bosco e Aldir Blanc)       
1. *Um por todos* (João Bosco e Aldir Blanc)           
1. *Violeta de Belford Roxo* (João Bosco e Aldir Blanc)        
1. *Zona de fronteira* (João Bosco, Antônio Cícero e Wally Salomão)       

### Milton Nascimento

[Site oficial](https://www.miltonnascimento.com.br/)

[Playlist](https://open.spotify.com/playlist/3JfQIADWnWdsTKNgOi8Iex)

1. *A lágrima e o rio* (Milton Nascimento, Wilson Lopes e Ricardo Nazar)
1. *Ao que vai nascer* (Milton Nascimento e Fernando Brant)         
1. *A sede do peixe* (Milton Nascimento e Márcio Borges) 
1. *A terceira margem do rio* (Milton Nascimento e Caetano Veloso) 
1. *Amor amigo* (Milton Nascimento e Fernando Brant) 
1. *Cadê* (Milton Nascimento e Ruy Guerra)     
1. *Cais* (Milton Nascimento e Ronaldo Bastos) 
1. *Canção amiga* (Milton Nascimento e Carlos Drumond de Andrade) 
1. *Catavento* (Milton Nascimento) 
1. *Caxangá* (Milton Nascimento e Fernando Brant)     
1. *Clube da Esquina n° 2* (Milton Nascimento, Lô Borges e Márcio Borges)  
1. *Coisas de Minas* (Milton Nascimento e Wilson Lopes)    
1. *Coração civil* (Milton Nascimento e Fernando Brant)  
1. *Cravo e canela* (Milton Nascimento e Ronaldo Bastos)     
1. *Credo* (Milton Nascimento e Fernando Brant)      
1. *Crença* (Milton Nascimento e Márcio Borges)   
1. *Dança dos meninos* (Milton Nascimento e Marco Antônio Guimarães)  
1. *E daí?* (Milton Nascimento e Ruy Guerra)     
1. *Estrelada* (Milton Nascimento e Márcio Borges)   
1. *Gira, girou* (Milton Nascimento e Márcio Borges)    
1. *Leila* (Milton Nascimento)      
1. *Lilia* (Milton Nascimento)         
1. *Maria, Maria* (Milton Nascimento e Fernando Brant)       
1. *Maria três filhos* (Milton Nascimento e Fernando Brant)      
1. *Milagre dos peixes* (Milton Nascimento e Fernando Brant)        
1. *Morro Velho* (Milton Nascimento)    
1. *Nada será como antes* (Milton Nascimento e Ronaldo Bastos)    
1. *Novena* (Milton Nascimento e Márcio Borges)        
1. *Olha* (Milton Nascimento) 
1. *O cavaleiro* (Milton Nascimento e Wilson Lopes)       
1. *Os povos* (Milton Nascimento e Márcio Borges)       
1. *Outubro* (Milton Nascimento e Fernando Brant)   
1. *Pelo amor de Deus* (Milton Nascimento e Fernando Brant)       
1. *Pietá* (Milton Nascimento e Chico Amaral)    
1. *Primeiro de maio* (Milton Nascimento e Chico Buarque)  
1. *Rio Vermelho* (Milton Nascimento, Danilo Caymmi e Ronaldo Bastos)  
1. *River Phoenix* (Milton Nascimento)         
1. *Roupa Nova* (Milton Nascimento e Fernando Brant)     
1. *Saídas e bandeiras* (Milton Nascimento e Fernando Brant)  
1. *San Vicente* (Milton Nascimento e Fernando Brant)         
1. *Saudades dos aviões da Panair* (Milton Nascimento e Fernando Brant) 
1. *Tarde* (Milton Nascimento e Márcio Borges)     
1. *Tema de Tostão* (Milton Nascimento e Matthew Moore)   
1. *Travessia* (Milton Nascimento e Fernando Brant) 
1. *Três Pontas* (Milton Nascimento e Ronaldo Bastos)      
1. *Tristesse* (Milton Nascimento e Telo Borges)    
1. *Um gosto de sol* (Milton Nascimento e Ronaldo Bastos)  
1. *Vera Cruz* (Milton Nascimento e Márcio Borges) 
1. *Vida* (Milton Nascimento e Fernando Brant)     
1. *Vidro e corte* (Milton Nascimento)       

### Gilberto Gil

[Site oficial](https://gilbertogil.com.br/)

[Playlist](https://open.spotify.com/playlist/37QMF6EuxOneQTLlFgLORg)

1. *Andar com fé* (Gilberto Gil)
1. *Aquele abraço* (Gilberto Gil)    
1. *Aqui e agora* (Gilberto Gil)  
1. *Babá Alapalá* (Gilberto Gil)  
1. *Back in Bahia* (Gilberto Gil)        
1. *Barato total* (Gilberto Gil)    
1. *Cérebro eletrônico* (Gilberto Gil)          
1. *Chororô* (Gilberto Gil)        
1. *Copo vazio* (Gilberto Gil)      
1. *Cores vivas* (Gilberto Gil)  
1. *Deixar você* (Gilberto Gil)       
1. *Divino e maravilhoso* (Gilberto Gil e Caetano Veloso)  
1. *Domingo no parque* (Gilberto Gil)        
1. *Drão* (Gilberto Gil)   
1. *Era nova* (Gilberto Gil)      
1. *Eu vim da Bahia* (Gilberto Gil)   
1. *Expresso 2222* (Gilberto Gil)       
1. *Extra* (Gilberto Gil)      
1. *Flora* (Gilberto Gil)   
1. *Ladeira da Preguiça* (Gilberto Gil)     
1. *Lamento sertanejo* (Gilberto Gil e Dominguinhos)   
1. *Lente do amor* (Gilberto Gil)  
1. *Louvação* (Gilberto Gil e Torquato Neto)           
1. *Luar* (Gilberto Gil)           
1. *Lugar comum* (Gilberto Gil e João Donato)       
1. *Mancada* (Gilberto Gil)  
1. *Meio de campo* (Gilberto Gil)      
1. *Menina do sonho* (Gilberto Gil)   
1. *Meu amigo, meu herói* (Gilberto Gil)     
1. *Morena* (Gilberto Gil e Cassiano)      
1. *O rouxinol* (Gilberto Gil e Jorge Mautner)      
1. *O sonho acabou* (Gilberto Gil)    
1. *Palco* (Gilberto Gil)       
1. *Pessoa nefasta* (Gilberto Gil)  
1. *Preciso aprender a ser só* (Gilberto Gil)   
1. *Procissão* (Gilberto Gil)  
1. *Punk da periferia* (Gilberto Gil)   
1. *Raça humana* (Gilberto Gil)  
1. *Rebento* (Gilberto Gil)      
1. *Refazenda* (Gilberto Gil)     
1. *Retiros espirituais* (Gilberto Gil)       
1. *Sandra* (Gilberto Gil)    
1. *Sarará miolo* (Gilberto Gil)            
1. *Se eu quiser falar com Deus* (Gilberto Gil)  
1. *Soy loco por ti, América* (Gilberto Gil e Capinam)    
1. *Super-homem, a canção* (Gilberto Gil)        
1. *Realce* (Gilberto Gil)       
1. *Sítio do Pica-Pau Amarelo* (Gilberto Gil)   
1. *Toda menina baiana* (Gilberto Gil)       
1. *Vamos fugir* (Gilberto Gil e Liminha)

### Rita Lee

[Site oficial](https://www.instagram.com/ritalee_oficial/)

[Playlist](https://open.spotify.com/playlist/5N3gtetTypnsFvI3Sl3bEQ?si=4412bbb41f774d18)

1. *Agora é moda* (Rita Lee e Lee Marcucci)
1. *Agora só falta você* (Rita Lee e Luiz Sérgio Carlini)
1. *Alô, alô marciano* (Rita Lee e Roberto de Carvalho)
1. *Ambição* (Rita Lee)
1. *Amor objeto* (Rita Lee e Roberto de Carvalho)
1. *Ando jururu* (Rita Lee)
1. *Ando meio desligado* (Rita Lee, Arnaldo Baptista e Sérgio Baptista)
1. *Arrombou a festa} (Rita Lee e Paulo Coelho)
1. *Baila comigo* (Rita Lee)
1. *Balada do louco* (Rita Lee e Arnaldo Baptista)
1. *Bandido corazón* (Rita Lee)
1. *Banho de espuma* (Rita Lee e Roberto de Carvalho)
1. *Barata tonta* (Rita Lee e Roberto de Carvalho)
1. *Brazil com s* (Rita Lee e Roberto de Carvalho)
1. *Bwana* (Rita Lee e Roberto de Carvalho)
1. *Caso sério* (Rita Lee e Roberto de Carvalho)
1. *Chega mais* (Rita Lee e Roberto de Carvalho)
1. *Com a boca no mundo* (Rita Lee, Luiz Sérgio Carlini e Lee Marcucci)
1. *Cor-de-rosa choque* (Rita Lee e Roberto de Carvalho)
1. *Corre-corre* (Rita Lee e Roberto de Carvalho)
1. *Dançar para não dançar} (Rita Lee)
1. *Desculpe o auê* (Rita Lee e Roberto de Carvalho)
1. *Doce vampiro* (Rita Lee)
1. *Esse tal de Roque Enrow* (Rita Lee e Paulo Coelho)
1. *Eu e meu gato* (Rita Lee)
1. *Flagra* (Rita Lee e Roberto de Carvalho)
1. *Fruto proibido* (Rita Lee)
1. *Jardins da Babilônia* (Rita Lee e Lee Marcucci)
1. *Lança perfume* (Rita Lee e Roberto de Carvalho)
1. *Livre outra vez* (Rita Lee e Roberto de Carvalho)
1. *Mamãe natureza* (Rita Lee)
1. *Mania de você* (Rita Lee e Roberto de Carvalho)
1. *Menino bonito* (Rita Lee)
1. *Miss Brasil 2000} (Rita Lee e Lee Marcucci)
1. *Mutante* (Rita Lee e Roberto de Carvalho)
1. *Nem luxo nem lixo* (Rita Lee e Roberto de Carvalho)
1. *O futuro me absolve* (Rita Lee)
1. *Orra meu* (Rita Lee)
1. *Ovelha negra* (Rita Lee)
1. *Papai me empresta o carro* (Rita Lee e Roberto de Carvalho)
1. *Pega rapaz* (Rita Lee e Roberto de Carvalho)
1. *Perigosa* (Rita Lee, Roberto de Carvalho e Nelson Motta)
1. *Perto do fogo* (Rita Lee e Cazuza)
1. *Saúde* (Rita Lee e Roberto de Carvalho)
1. *Shangrilá* (Rita Lee e Roberto de Carvalho)
1. *Só de você* (Rita Lee e Roberto de Carvalho)
1. *Te contei* (Rita Lee e Roberto de Carvalho)
1. *Tititi* (Rita Lee e Roberto de Carvalho)
1. *Vote em mim* (Rita Lee, Roberto de Carvalho e Ezequiel Neves)
1. *Xuxuzinho* (Rita Lee e Roberto de Carvalho) 

### Carlos Lyra

[Site oficial](http://www.carloslyra.com/)

[Playlist](https://open.spotify.com/playlist/53VD1fHd6fRlXIYkkbnmKg?si=c32ce521523f41de)

1. *Até parece* (Carlos Lyra)
1. *Barquinho de papel* (Carlos Lyra)
1. *Broto maroto* (Carlos Lyra e Vinicius de Moraes)
1. *Broto triste* (Carlos Lyra e Vinicius de Moraes)
1. *Canção do amor* que chegou (Carlos Lyra e Vinicius de Moraes)
1. *Canção que morre no ar* (Carlos Lyra e Ronaldo Bôscoli)
1. *Cara bonita* (Carlos Lyra)
1. *Cartão de visitas* (Carlos Lyra e Vinicius de Moraes)
1. *Ciúme* (Carlos Lyra)
1. *Coisa mais linda* (Carlos Lyra e Vinicius de Moraes)
1. *Entrudo* (Carlos Lyra e Ruy Guerra)
1. *Essa passou* (Carlos Lyra e Chico Buarque)
1. *Feio não é bonito* (Carlos Lyra e Gianfrancesco Guarnieri)
1. *Influência do jazz* (Carlos Lyra)
1. *Lamento de um homen só* (Carlos Lyra e Vinicius de Moraes)
1. *Lobo bobo* (Carlos Lyra e Ronaldo Bôscoli)
1. *Marcha de Quarta-feira de Cinzas* (Carlos Lyra e Vinicius de Moraes)
1. *Maria Moita* (Carlos Lyra e Vinicius de Moraes)
1. *Maria ninguém* (Carlos Lyra)
1. *Minha namorada* (Carlos Lyra e Vinicius de Moraes)
1. *Nada como ter amor* (Carlos Lyra e Vinicius de Moraes)
1. *O negócio é amar* (Carlos Lyra e Dolores Duran)
1. *Pobre menina rica* (Carlos Lyra e Vinicius de Moraes)
1. *Pode ir* (Carlos Lyra e Vinicius de Moraes)
1. *Primavera* (Carlos Lyra e Vinicius de Moraes)
1. *Primeira namorada* (Carlos Lyra e Vinicius de Moraes)
1. *Sabe você* (Carlos Lyra e Vinicius de Moraes)
1. *Saudade fez um samba* (Carlos Lyra e Ronaldo Bôscoli)
1. *Se é tarde, me perdoa* (Carlos Lyra e Ronaldo Bôscoli)
1. *Você e eu* (Carlos Lyra e Vinicius de Moraes)

### Dori Caymmi

[Site oficial](https://www.instagram.com/dori_caymmi_oficial_/)

[Playlist](https://open.spotify.com/playlist/1WMrHWWujDDad3dKwNn0IN?si=8be1bfe6d4ff473a)

1. *Alegre meninia* (Dori Caymmi e Jorge Amado)
1. *Armadilhas de um romance* (Dori Caymmi e Paulo César Pinheiro)
1. *Coração sem saída* (Dori Caymmi e Paulo César Pinheiro)
1. *Dança do tucano (Dori Caymmi e Paulo César Pinheiro)
1. *Delicadeza* (Dori Caymmi e Paulo César Pinheiro)
1. *Desafio* (Dori Caymmi e Paulo César Pinheiro)
1. *Desenredo* (Dori Caymmi e Paulo César Pinheiro)
1. *Evangelho* (Dori Caymmi e Paulo César Pinheiro)
1. *Estrela da terra* (Dori Caymmi e Paulo César Pinheiro)
1. *Flor da Bahia* (Dori Caymmi e Paulo César Pinheiro)
1. *Fora de hora* (Dori Caymmi e Chico Buarque)
1. *História antiga* (Dori Caymmi e Paulo César Pinheiro)
1. *Mercador de siri* (Dori Caymmi e Paulo César Pinheiro)
1. *Na ribeira deste rio* (Dori Caymmi e Fernando Pessoa)
1. *Ninho de vespa* (Dori Caymmi e Paulo César Pinheiro)
1. *O cantador* (Dori Caymmi e Nelson Motta)
1. *Porto* (Dori Caymmi)
1. *Quebra-mar* (Dori Caymmi e Paulo César Pinheiro)
1. *Rio Amazonas* (Dori Caymmi e Paulo César Pinheiro)
1. *Saudade de amar* (Dori Caymmi e Paulo César Pinheiro)
1. *Saudade do Rio* (Dori Caymmi e Paulo César Pinheiro)
1. *Saveiros* (Dori Caymmi e Nelson Motta)
1. *Tati, a garota* (Dori Caymmi e Paulo César Pinheiro)
1. *Três curumins* (Dori Caymmi e Paulo César Pinheiro)
1. *Velho piano* (Dori Caymmi e Paulo César Pinheiro)
1. *Voz de mágoa* (Dori Caymmi e Paulo César Pinheiro)

### Cartola

[Playlist](https://open.spotify.com/playlist/62oBMILQf5tarcHSrvZDwj?si=94584df696bb4b4a)

1. *A cor da esperança* (Cartola e Roberto Nascimento)
1. *Acontece* (Cartola)
1. *Alvorada* (Cartola e Carlos Cachaça e Hermínio Bello de Carvalho)
1. *Amor proibido* (Cartola)
1. *As rosas não falam* (Cartola)
1. *Disfarça e chora* (Cartola e Dalmo Castello)
1. *Divina dama* (Cartola)
1. *Ensaboa mulata* (Cartola)
1. *Festa da vinda* (Cartola e Nuno Velloso)
1. *Minha* (Cartola)
1. *O inverno do meu tempo* (Cartola e Roberto Nascimento)
1. *O mundo é um moinho* (Cartola)
1. *O sol nascerá* (Cartola e Elton Medeiros)
1. *Peito vazio* (Cartola e Elton Medeiros)
1. *Preconceito* (Cartola)
1. *Quem me vê sorrindo* (Cartola)
1. *Sei chorar* (Cartola)
1. *Sim* (Cartola e Oswaldo Martins)
1. *Tive sim* (Cartola)
1. *Verde que te quero rosa* (Cartola e Dalmo Castello)

### Gonzaguinha

[Site oficial](https://gonzaguinha.com.br/)

[Playlist](https://open.spotify.com/playlist/5KvSiknWfKc4jjClRhRzCW?si=61f5c5c749334b87)

1. *Artistas da vida* (Gonzaguinha)
1. *Caminhos do coração* (Gonzaguinha)
1. *Com a perna no mundo* (Gonzaguinha)
1. *Comportamento geral* (Gonzaguinha)
1. *Comecaria tudo outra vez* (Gonzaguinha)
1. *Deixa Dilson e vamos Nelson* (Gonzaguinha)
1. *Dias de Santos e Silvas* (Gonzaguinha)
1. *Diga lá, coração* (Gonzaguinha)
1. *Espere por mim* (Gonzaguinha)
1. *Eu apenas queria que você soubesse* (Gonzaguinha)
1. *E vamos à luta* (Gonzaguinha)
1. *Grito de alerta* (Gonzaguinha)
1. *Lindo lago do amor* (Gonzaguinha)
1. *Não dá mais pra segurar* (Gonzaguinha)
1. *O preto que satisfaz* (Gonzaguinha)
1. *O que é o que é* (Gonzaguinha)
1. *Ponto de interrogação* (Gonzaguinha)
1. *Recado* (Gonzaguinha)
1. *Sangrando* (Gonzaguinha)
1. *Um homem também chora* (Gonzaguinha)


-----

## Grupos de controle

### Jazz
1. *A child is born* (Thad Jones)
1. *A foggy day* (George Gershwin)    
1. *A night in Tunisia* (Dizzy Gillespie)       
1. *Afternoon in Paris* (John Lewis)  
1. *All of me in Paris* (Seymour Simons e Gerald Marks)    
1. *All the things you are* (Jerome Kern e Oscar Hammerstein II)  
1. *Anthropology* (Charlie Parker)    
1. *April in Paris* (Vernon Duke e Edgard Harburg)      
1. *As time goes by* (Herman Hupfeld)      
1. *Bewitched* (Richard Rodgers e Lorenz Hart)      
1. *Bluesette* (Toots Thielemans)      
1. *Blues for Alice* (Toots Thielemans)    
1. *Body and soul* (Johnny Green, Edward Heyman, Robert Sour e Frank Eyton)
1. *Cottontail* (Duke Ellington)   
1. *Could it be you* (Cole Porter)  
1. *Countdown* (John Coltrane)  
1. *Crystal silence* (Chick Corea)      
1. *Days of wine and roses* (Henry Mancini)  
1. *Dexterity* (Charlie Parker)     
1. *Dolphin dance* (Herbie Hancock)    
1. *The duke* (Dave Brubeck)    
1. *Easy to love* (Cole Porter)     
1. *Five hundred miles high* (Chick Corea)      
1. *For heaven's sake* (Sherman Edwards e Elise Bretton)      
1. *Four* (Miles Davis)    
1. *Giant steps* (John Coltrane)  
1. *Goodbye pork pie hat* (Charles Mingus) 
1. *Have you met Miss Jones?* (Richard RChoroodgers e Lorenz Hart)   
1. *How high the moon* (Morgan Lewis e Nancy Hamilton)
1. *I can't get started* (Vernon Duke e Ira Gershwin)      
1. *I love you* (Cole Porter)      
1. *In a sentimental mood* (Duke Ellington)         
1. *In your own sweet way* (Dave Brubeck)
1. *Long ago and far away* (Jerome Kern)
1. *Misty* (Errol Garner)    
1. *Mood indigo* (Duke Ellington)  
1. *My funny Valentine* (Richard Rodgers e Lorenz Hart)     
1. *Night and day* (Cole Porter)    
1. *Ornithology* (Charlie Parker)
1. *Pensativa* (Clare Fisher)
1. *Peri's cope* (Bill Evans)    
1. *Prelude to a kiss* (Duke Ellington)
1. *Played twice* (Thelonious Monk)  
1. *Round midnight* (Thelonious Monk)    
1. *Satin doll* (Duke Ellington)     
1. *Semblence* (Keith Jarrett)  
1. *The shadow of your smile* (Johnny Mandel e Paul Francis Webster)
1. *The song is you* (Jerome Kern e Oscar Hammerstein III) 
1. *The sorcerer* (Herbie Hancock)    
1. *Time remembered* (Bill Evans) 



### Choro
1. *Abraçando jacaré* (Pixinguinha)
1. *Agradecendo* (Pixinguinha)    
1. *Ainda me recordo* (Pixinguinha e Benedito Lacerda)   
1. *Ande ligeiro* (Pixinguinha)  
1. *As proezas de Nolasco* (Pixinguinha)           
1. *Atencioso* (Pixinguinha)        
1. *A vida é um buraco* (Pixinguinha)    
1. *Bom senso* (Pixinguinha)           
1. *Canto em rodeio* (Pixinguinha)              
1. *Carinhoso* (Pixinguinha e João de Barro)           
1. *Cascatinha* (Pixinguinha)   
1. *Cheguei* (Pixinguinha e Benedito Lacerda)     
1. *Chorando sempre* (Pixinguinha)  
1. *Chorei* (Pixinguinha e Benedito Lacerda)     
1. *Choro de gafieira* (Pixinguinha)  
1. *Concerto de baterias* (Pixinguinha)  
1. *Cuidado, colega* (Pixinguinha e Benedito Lacerda)         
1. *Descendo a serra* (Pixinguinha e Benedito Lacerda)   
1. *Desprezado* (Pixinguinha)       
1. *Destino da rosa* (Pixinguinha)      
1. *Devagar e sempre* (Pixinguinha e Benedito Lacerda)   
1. *Diabólica* (Pixinguinha) 
1. *Dininha* (Pixinguinha e Benedito Lacerda)      
1. *Dominó* (Pixinguinha) 
1. *É isso mesmo* (Pixinguinha)     
1. *Ele e eu* (Pixinguinha e Benedito Lacerda)   
1. *Fonte abandonada* (Pixinguinha)     
1. *Gargalhada* (Pixinguinha)     
1. *Generoso* (Pixinguinha)     
1. *Homenagem à flor margarida* (Pixinguinha) 
1. *Ingênuo* (Pixinguinha e Benedito Lacerda) 
1. *Joaquim virou padre* (Pixinguinha) 
1. *Jurando falso* (Pixinguinha)       
1. *Lamentos* (Pixinguinha e Vinicius de Moraes) 
1. *Minha vez* (Pixinguinha)  
1. *Naquele tempo* (Pixinguinha e Benedito Lacerda) 
1. *Não vou nessa* (Pixinguinha) 
1. *Os cinco companheiros* (Pixinguinha)   
1. *Os oito batutas* (Pixinguinha e Benedito Lacerda) 
1. *Oscarina* (Pixinguinha e Benedito Lacerda) 
1. *Pagão* (Pixinguinha e Benedito Lacerda)      
1. *Parangolé* (Pixinguinha)   
1. *Passa tempo* (Pixinguinha)   
1. *Pretensioso* (Pixinguinha)   
1. *Proezas de Solon* (Pixinguinha e Benedito Lacerda)         
1. *Quem é você* (Pixinguinha)   
1. *Rir pra não chorar* (Pixinguinha)   
1. *Segura ele* (Pixinguinha e Benedito Lacerda)   
1. *Seu Lourenço do vinho* (Pixinguinha e Benedito Lacerda)  
1. *Vou vivendo* (Pixinguinha e Benedito Lacerda)       

### Samba
1. *Abre a janela* (Roberto Roberti e Arlindo Marques Júnior)
1. *Acreditar* (Délcio Carvalho e Dona Ivone Lara)     
1. *Adeus batucada* (Synval Silva)       
1. *A flor e o espinho* (Nelson Cavaquinho, Guilherme de Brito e Alcides Caminha)   
1. *Agoniza mas não morre* (Nelson Sargento)   
1. *Agora é cinza* (Bide e Marçal) 
1. *Água na boca* (Agildo Mendes) 
1. *Ai que saudades da Amélia* (Ataulfo Alves e Mário Lago) 
1. *Alguém me avisou* (Dona Ivone Lara)       
1. *Alô, alô* (Mario Reis e André Filho)        
1. *Amor aventureiro* (Mano Décio da Viola e Silas de Oliveira) 
1. *Amor de poeta* (Sinhô) 
1. *Apoteose ao samba* (Silas de Oliveira e Mano Décio de Carvalho)        
1. *A primeira vez* (Alcebíades Barcelos e Armando Marçal)    
1. *A vida me fez assim* (Teresa Cristina e Argemiro)      
1. *A voz do morro* (Zé Keti)   
1. *Brasil pandeiro* (Assis Valente)      
1. *Beija-me* (Mário Rossi e Roberto Martins)   
1. *Cabide de mulambo* (João da Baiana)   
1. *Camisa amarela* (Ary Barroso)    
1. *Canta, canta, minha gente* (Martinho da Vila)     
1. *Coisa de pele* (Acyr Marques e Jorge Aragão)     
1. *Confessa, meu bem* (Sinhô)   
1. *Coisa da antiga* (Nei Lopes e Wilson Moreira)      
1. *Essa nega qué me dá* (Caninha)   
1. *Eu queria um retratinho de você* (Noel Rosa)   
1. *Exaltação à Mangueira* (Enéas Brites da Silva e Aluízio Augusto da Costa)     
1. *Fala, meu louro* (Sinhô)   
1. *Falsa baiana* (Geraldo Pereira)  
1. *Feitio de oração* (Noel Rosa)    
1. *Festa para um rei negro* (Zuzuca)  
1. *Filosofia* (Noel Rosa)    
1. *Foi um rio que passou em minha vida* (Paulinho da Viola)      
1. *Jura* (Sinhô)   
1. *Isaura* (Roberto Roberti e Herivelto Martins)  
1. *Lá vem a baiana* (Dorival Caymmi)       
1. *Macaco, olha teu rabo* (Chico da Baiana)   
1. *Me deixa em paz* (Monsueto Menezes e Ayrton Amorim)      
1. *Mora na filosofia* (Monsueto Menezes e Arnaldo Passos) 
1. *Nega maluca* (Fernando Lobo e Evaldo Ruy)        
1. *O meu nome já caiu no esquecimento* (Paulo da Portela)   
1. *Os cinco bailes da história do Rio* (Silas de Oliveira, Bacalhau e Dona Ivone Lara)     
1. *Palpite infeliz* (Noel Rosa)   
1. *Papagaio come milho* (Chico da Baiana)       
1. *Pelo telefone* (Donga)      
1. *Quem são eles* (Sinhô)      
1. *Rapaz folgado* (Noel Rosa)        
1. *Se acaso você chegasse* (Lupicínio Rodrigues e Felisberto Martins)
1. *Se você jurar* (Ismael Silva)       
1. *Vai saudade* (Heitor dos Prazeres)        
