---
title: N-gramas
---

## Introdução


*N-gramas* (ou *n-grams* em sua versão original, em inglês) podem ser basicamente definidos como sequências contíguas de *n* elementos. Tal conceito pode ser aplicado a qualquer sequência de símbolos, como acontece em textos (a aplicação original), mas também em outros tipos de informação simbólica notada sequencialmente,  como se observa em música, o que se associa diretamente a nossos interesses. O valor de *n* no termo indica, propriamente, o número de transições da sequência, sendo n+1 o número de elementos envolvidos. Assim, podemos ter sequências do tipo 0-grama (nenhuma transição, ou seja, apenas um elemento), 1-grama (uma transição, dois elementos), 2-grama (duas transições contíguas, três elementos) e assim por diante.

O conceito de n-gramas tem suas origens na teoria da probabilidade e na linguística computacional, remontando -- assim como a ideia de *entropia* (ver capítulo [Probabilidade e entropia](probabilidade.qmd)) -- às primeiras formulações de Claude Shannon na década de 1940 sobre Teoria da Informação, a partir de uma intenção de quantificar a redundância em sequências de símbolos em textos. Na década de 1950 e 1960, com o surgimento da linguística computacional, os n-gramas foram empregados para modelar a linguagem natural, o que foi principalmente aperfeiçoado pelo trabalho de George Kingsley Zipf,^[Ver @zipf-psycho.] que observou padrões na frequência das palavras em textos em inúmeros livros, independentemente de época ou de idioma em que foram escritos. 

No contexto do Projeto MPB........
