---
title: "A ''nossa'' MPB"
---

Parece paradoxal o fato de a presente proposta -- cuja essência e principal finalidade envolvem um tratamento profundamente objetivo dos dados analíticos -- ser desenvolvida sobre um terreno tão fluido e incerto quanto é o contexto da MPB. Como previamente comentado, a tarefa de estabelecer as fronteiras históricas desse conceito esbarra em inúmeros problemas. A bem da verdade, nem ao menos a pura "existência" da MPB pode ser considerada um fato consensual: não rara é a opinião de que trata-se de um mero constructo cultural, criado num determinado contexto político, com objetivos comerciais. Não, não pretendemos entrar nesses pormenores, muito menos debater questões tão básicas e existencialistas como essa.

Se por um lado, tais indefinições promovem uma certa insegurança sobre o próprio objeto de estudo, por outro, podemos aproveitar justamente dessa inerente fluidez e multiplicidade interpretativa para nos posicionarmos, por assim dizer, de um modo relativamente confortável. Ou seja, propomos aqui neste capítulo o estabelecimento de uma perspectiva particular sobre a MPB, o que nos levará, entre outras coisas, a definir as fronteiras que consideramos adequadas a tal viés: em outros termos, este capítulo apresentará a "nossa" MPB. Enfatizamos aqui que não é, de modo algum, nossa intenção contrariar quaisquer versões distintas e/ou conflitantes sobre o assunto. Muito menos nossa proposta baseia-se em novos elementos, descobertas ou pesquisas acadêmicas especializadas (musicológicas, historiográficas, sociológicas etc.). Trata-se, sim, de uma visão por certo idiossincrática, porém não desprovida de lógica ou desvinculada dos fatos e contextos envolvidos.

Antes de partir propriamente para uma definição, no entanto, vale a pena relembrar alguns pontos levantados na introdução do projeto. Talvez o mais importante deles seja o quão culturalmente compartilhada é a noção do que seria uma composição *emepebística*: com base no que conhecemos, é possível pensar que uma pessoa que tenha nascido e/ou que vive no Brasil seja razoavelmente capaz de reconhecer informalmente se uma determinada canção, que ouve pela primeira vez, seria ou não "de MPB", caso essas opções sejam oferecidas. É claro que a maior ou menor eficácia desse "experimento" informal flutuaria de acordo com a época, a idade, os níveis sócio-econômico e de escolaridade da pessoa testada, mas é perfeitamente viável crer que essa noção ainda se mantenha razoavelmente estável em nossa cultura a despeito dessas flutuações, o que denota que, mesmo sem conhecer (ou poder identificar) aspectos específicos estruturais da construção musical dessas peças, em média, sabemos intimamente (ou, pelo menos, temos uma boa ideia de) o que elas têm de diferente em relação às demais músicas, "não-emepebísticas", enfim.

Outro ponto importante levantado na introdução -- e que merece ser aqui retomado -- diz respeito à extraordinária diversidade do "meio-ambiente" da MPB, um aspecto notável que contribui para dificultar a definição de suas fronteiras. O nosso subconjunto-alvo (adiantando, sem prejuízo, um termo do próximo capítulo) é um amálgama extremamente amplo de personalidades e estilos composicionais, gêneros musicais e movimentos estéticos, formando um quadro de grande complexidade. Reiteramos, portanto, que a MPB não pode ser chamada de um estilo (é uma combinação de um número incalculável deles), muito menos de um gênero (que convivem, em grande quantidade, harmoniosamente debaixo do "guarda-chuva" emepebístico). O que talvez seja um aspecto inovador de nossa proposta é sustentar que a MPB também não é uma estética ou um movimento: ela *abarca* estéticas e movimentos que, não necessariamente se alternam; na verdade, também observamos que diversas correntes estéticas, ainda que apresentem maior ou menor proeminência em determinados momentos ao longo do tempo, formam nichos que seguem sem maiores disputas ou conflitos sob o mesmo "teto".

Essa perspectiva nos leva a uma questão central da proposta, que é o estabelecimento do território de estudo. Afinal, a que período histórico está associada a MPB? No excelente e completíssimo *A história da música popular brasileira* (volume I), Rodrigo Faour tem o cuidado de, ao se referir à MPB, sempre grafar o termo entre aspas, de modo a diferenciar esse conceito específico do que considera como as Músicas Populares Brasileiras, uma acepção globalizante da produção musical no Brasil, uma tese que de algum modo se assemelha à nossa, ao menos em linhas gerais. Faour dedica um capítulo à descrição pormenorizada de sua "MPB", circunscrevendo-a na década de 1970 (1970-78, mais precisamente), ainda que implicitamente reconheça sua sobrevida em períodos posteriores.

Nesse viés, a "MPB" de Faour é tratada como um movimento -- aqui, portanto, distinguindo-se de nossa visão --, equiparando-se a outros, como a "Era do rádio", a "Bossa nova", a "Jovem guarda" etc. Depreende-se de seu texto que o movimento teve sua origem associada ao turbulento contexto político da época, com uma produção marcada, ao menos inicialmente, por canções de protesto e de resistência à ditadura. De acordo com nossa argumentação, entendemos a MPB como uma noção num nível mais elevado em relação aos movimentos e estéticas, o que nos faz considerar seus limites temporais de uma maneira mais flexível.[^1]

Talvez o aspecto mais saliente de nossa ótica se refira justamente à questão que envolve o gênero (ou subgênero, derivado do samba) e/ou a estética da bossa nova. Para nós, a bossa nova *integra* o subconjunto-alvo da MPB, entre outros membros de mesma magnitude (sejam gêneros, como blues, baião, frevo, samba etc.; sejam estéticas, como a do "Clube da Esquina", por exemplo) uma opinião que provavelmente fará levantar as sobrancelhas de alguns leitores. Nesse sentido, a obra de Tom Jobim parece nos dar razão. Normalmente identificado como "o principal compositor de bossa nova" (o que não deixa de ser verdade), Jobim raramente é também lembrado por ter composto em um grande número de estéticas e gêneros. De fato, a partir de 1968, com sua obra-prima *Sabiá* (em coautoria de Chico Buarque), Jobim claramente começou a se distanciar da estética bossanovista (intenção que, aliás, expressou claramente em vários depoimentos). Afinal, faz sentido classificar, por exemplo, *Luiza*, *Passarim*, *Chovendo na roseira*, *Matita Perê*, entre tantos outros títulos como bossas? Apenas a acomodação às facilidades da rotulação poderia explicar essas imprecisões, que infelizmente se perpetuam na crítica musical e mesmo no meio acadêmico.

Pois bem, a trajetória de Jobim, ou melhor, de seu *estilo composicional*, é um perfeito representante da ideia que temos sobre os membros do subconjunto MPB e, principalmente, de seu âmbito temporal dentro da música brasileira. Se tomarmos o ano de 1973 como ponto de referência -- fazendo uma pertinente alusão a outro ótimo livro recentemente publicado (2015) sobre o tema, intitulado *1973: o ano que inventou a MPB*, de Célio Albuquerque -- e traçarmos um círculo com raio de 20 anos, obteremos aproximadamente o período criativo de Jobim, entre 1953 e 1993, abarcando 40 anos de produção composicional. Parece-nos um recorte bastante adequado a nossos propósitos analíticos, especialmente pelo fato de alçar o nosso grande mestre (o maior de todos, sem qualquer dúvida, dentro do riquíssimo universo da música brasileira) à posição privilegiada de eixo sobre o qual se constrói nossa ideia particular sobre o período da Prática Comum da MPB, como sugere a Figura XXXX.

**TEXTO A SER COMPLETADO**

[^1]: A bem da verdade, o entendimento sobre a "MPB" por Faour se aproxima do nosso, o que se evidencia especialmente no volume II de seu livro (que parte dos anos 1970 e alcança 2020). Em quase todos os capítulos, a herança emepebística é posta em destaque, em hibridação com diversas estéticas ao longo das décadas cobertas (por exemplo, considerando o forte movimento do rock no Brasil, nos anos 1990).
