---
title: Produção bibliográfica
---
## 2025

### Livros
#### Funcionalidade harmônica em música popular: uma proposta teórica
Carlos Almada

Editora da Unicamp

**Resumo**: Este livro apresenta uma perspectiva original e inédita sobre o campo de estudos da harmonia na música popular, formalizando uma proposta de teoria cuja essência é a ideia de funcionalidade, tratada de maneira abrangente e aprofundada. Construída a partir da observação da prática harmônica estendida em música popular, essa teoria é estruturada como um amplo conjunto de princípios e novos conceitos, tais como a ideia de uma detalhada taxonomia de classes, subclasses e categorias funcionais, a sistematização de funções melódicas, bem como formulações referentes a expectativa contextual e níveis de organização funcional, entre outros aspectos. No livro, a noção de funcionalidade é ainda generalizada e estendida a contextos modais e coleções não diatônicas (simétricas ou não), o que gera novas abordagens teóricas e analíticas.


### Trabalhos em anais de congresso
Hugo Carvalho; Felipe Martins Carlos Almada  

#### A Corpus Study of Rhythm in Brazilian Popular Music. 

In: Latin American Music Information Retrieval Workshop, 1. Rio de Janeiro: Universidade Federal do Rio de Janeiro, 2024. Proceedings..., Rio de Janeiro: 2025.
[https://zenodo.org/records/14908040]

**Abstract**: The MPB Project (from the Brazilian Portuguese Música
Popular Brasileira) is a broad corpus study intended to
systematically analyze a large group of musical attributes
(regarding harmony, melody, and rhythm) in order to map
stylistic characteristics of renowned Brazilian composers
of popular music. The present work focuses on the rhyth-
mic structure, describing concisely the scope of the project
and some of the most important elements, like corpora for-
mation, datasets, methodological tools, analytical criteria,
conceptual framework, and some of the results obtained so
far, which in accordance with what we believe would be
the expectations of someone familiarized with the style.


## 2024

### Artigos

#### Apontamentos para uma teoria da forma em música popular
Carlos de Lemos Almada

Orfeu, v. 9 n. 2 (DOI: [https://doi.org/10.5965/2525530409022024e0105](https://doi.org/10.5965/2525530409022024e0105)

**Resumo**: Este  artigo  integra  uma  pesquisa  abrangente  sobre  a  estrutura  da  Música  Popular Brasileira (MPB), focando em as-pectos da forma. O estudo, que pretende essencialmente estabelecer uma base sóli-da para uma teoria sobre forma em música popular, é motivado pela escassa literatura específica sobre o assunto e toma como principais referenciais para suas formula-ções conceitos e pressupostos derivados da assim chamada Neue Formenlehre. Ini-ciando com um grupo de definições básicas (forma nominal, camadas e níveis estruturas, relações S/C e fatores de segmentação), o estudo propõe tipologias referentes às ideias de macro e microformas, concentrando-se especialmente neste último aspecto, ao qual se associa a dualidade conceitual períodoe sentença (SCHOENBERG, 1967; CAPLIN, 1998). Como ponto central de discussão, propomos uma perspectiva mais flexível para ambos os conceitos, a partir da ob-servação da prática musical no contexto da MPB. A construção de um modelo analítico voltado para as formulações propostas e sua aplicação em quatro estudos de caso são contemplados nas seções finais do artigo.

#### Função, expectativa e contexto na harmonia em música popular
Carlos de Lemos Almada

Musica Theorica, v. 9 n. 1 (DOI: [https://doi.org/10.52930/mt.v9i1](https://doi.org/10.52930/mt.v9i1))

**Resumo**: Este artigo discute o papel que as noções de expectativa e contexto exercem na determinação da funcionalidade, considerando condições encontradas especialmente na harmonia estendida da música popular. A partir da ideia de que a análise harmônica nesses contextos pode ser estratificada em diferentes níveis de observação e com o suporte de estudos sobre estrutura harmônica, probabilidade e cognição musical (considerando os conceitos de interesse do trabalho), são propostos tipologias específicas e um modelo analítico, aplicado na seção conclusiva.

### Monografias, teses e dissertações
#### Identificação de Acordes via Modelos de Markov Ocultos Musicalmente Informados
Rodrigo Côrtes Nogueira da Rocha Pita

Trabalho de Conclusão de Curso -- Bacharelado em Ciência da Computação

**Resumo**: Este projeto visa abordar o problema da identificação de acordes através de modelos de Markov ocultos (HMM) musicalmente informados. Para que seja um projeto autocontido, serão explicados três grandes tópicos. Primeiramente, as noções básicas de teoria musical, como intervalos e progressão harmônica. Em segundo lugar, o processamento de sinais de áudio, abordando transformadas de Fourier para em seguida poder apresentar a transformada de Fourier de tempo curto (STFT) e também cromagramas, que empenham um papel fundamental para o funcionamento do modelo HMM. Por fim, em terceiro, as cadeias de Markov, que são a base para o entendimento de HMMs. Para embutir a informação musical no modelo, será utilizada uma matriz de transição gerada a partir de uma base de músicas da MPB. Os experimentos realizados serão feitos inicialmente num contexto geral, com músicas de gêneros diversos com o intuito de comparar os modelos HMM e *template-based* assim como os diferentes tipos de cromagrama. Depois serão realizados somente no contexto da MPB, onde os resultados provarão a eficácia da proposta.

Códigos disponíveis no [GitHub do autor](https://github.com/RodrigoPita/TCC).

## 2023

### Livros
#### A melodia de Jobim
Carlos Almada

Editora da Unicamp

**Resumo**: A melodia de Jobim dá seguimento ao livro A harmonia de Jobim, publicado em 2022. Ambos resultam de pesquisa voltada para um exame original e detalhado de aspectos diversos da estrutura da obra de Antonio Carlos Jobim. O livro descreve em sua primeira parte os modelos teóricos elaborados ao longo da pesquisa, destinados à análise sistemática das estruturas de alturas e rítmicas de um corpus de composições jobinianas, incluindo várias peças não publicadas. A segunda parte é voltada especialmente a abordagens analíticas focalizando aspectos específicos da organização melódica, a saber, configurações de contornos, apoios em tensões harmônicas, linhas cromáticas, configurações formais e temáticas, derivação motívica e relações entre melodia e texto.

### Artigos
#### O ritmo de ideias básicas de samba: uma abordagem sistemática
Carlos de Lemos Almada e Pedro Zisels Ramos

Musica Theorica, v. 8 n. 1 (DOI: [https://doi.org/10.52930/mt.v8i1.261](https://doi.org/10.52930/mt.v8i1.261))

**Resumo**: Integrando uma pesquisa detalhada sobre aspectos estruturais do gênero samba, o presente artigo propõe um recorte no qual é enfocada apenas as configurações rítmicas das ideias básicas (Caplin 1998) de 500 sambas selecionados. A partir de um modelo teórico original e ferramentas computacionais especialmente desenvolvidas, o estudo analisa a construção rítmica das canções selecionadas, considerando diversos níveis de organização e suas combinações. Gráficos e quadros comparativos fornecem um inédito e sistemático painel sobre o ritmo do samba, elencando ainda algumas hipóteses que alimentarão estudos futuros.

### Apresentações em congressos

#### La armonía en Jobim: Análisis estadístico
Carlos Almada, Hugo Carvalho e Frederico Garcia

XXV Congreso Argentino de Musicologia

**Resumo** (em Espanhol): Desde 2022, un equipo liderado por Carlos Almada y Hugo Carvalho ha compilado el comportamiento armónico de un corpus de 50 canciones de Antonio Jobim (1927-1994) en un formato digital, generando una base de datos con la información completa de las progresiones bicordales presentes en ese repertorio. La presente ponencia da cuenta de la adaptación mutua entre ese base de datos y la herramienta de análisis computacional *Harmonic Profile Project* ([www.hpp pythonanywhere.com](www.hpp.pythonanywhere.com)), desarrollada por Federico García desde 2020, que genera visualizaciones, en 3 dimensiones e interactivas, del comportamiento arm ́onico de un corpus dado.

Los análisis estadísticos de la armonía aparecidos a la fecha (p.ej. los citados en la bibliografía) se han enfocado en tablas de dos dimensiones, clasificando las armonías en términos de una tónica central, usualmente a través de números romanos. Esto introduce sesgos estadísticos en pasajes con ultracromatismo, modulaciones intermitentes, y otras modalidades de ambigüedad tonal, lo cual hace que resulte problemático aplicar esos modelos a la música del Siglo XIX y a los lenguajes del Jazz, incluido por supuesto Jobim.

En vista de estas deficiencias, los presentes autores han investigado la armonía sin referencia a una tónica central, documentando y analizando las progresiones como información de tres (no sólo dos) parámetros: acorde de partida, acorde de llegada, y -- dado que ya no aparece codificada por los números romanos -- distancia interválica. La base de datos de Almada y Carvalho está diseñada en este sentido, y así mismo el HPP de García persigue justamente la manipulación y el análisis de información en las tres dimensiones, sin necesidad de forzar la clasificación de la cualidad y las distancias entre acordes dentro de una tonalidad.

La presente ponencia ofrece los primeros resultados del análisis estadístico de la armonía de Jobim (compilada en una base de datos que incluye 2320 acordes de 75 tipos distintos, y un total de 438 relaciones binarias en 56 categorías funcionales), así como una discusión teórica más general sobre las similitudes y diferencias entre el léxico y la sintaxis del jazz y los de la armonía tonal clásica, a partir de las adaptaciones que fueron necesarias en la interpretación de la armonía de Jobim dentro el sistema del *Harmonic Profile Project*.

#### Mapeamento de estilo na Prática Comum da MPB
de Carlos Almada, Hugo Carvalho e Cecília Saraiva

V Encontro da Associação Brasileira de Teoria e Análise Musical

#### Mapeamento de estruturas melódicas da MPB
Gabriel Barbosa

12ª Semana de Integração Acadêmica da UFRJ – SIAC 2023

## 2022

### Livros
#### A harmonia de Jobim

Carlos Almada

Editora da Unicamp

**Resumo**: A música de Antonio Carlos Jobim é mundialmente reconhecida por sua extraordinária beleza e originalidade. No entanto, sua estrutura ainda hoje carece de estudos técnicos que a examinem com os devidos detalhamento e profundidade. A harmonia de Jobim busca contribuir para suprir essa lacuna, propondo um estudo teórico-analítico sobre a construção harmônica desse grande compositor. O livro apresenta, em sua primeira parte, dois modelos teóricos originais, elaborados a partir do exame dos dados coletados em uma análise de 145 canções de Jobim e parceiros. A segunda parte é dedicada à funcionalidade harmônica dos campos tonais e das relações entre regiões, bem como ao peculiar modalismo jobiniano, alternando formulações conceituais e análises. Algumas abordagens específicas formam a terceira parte do volume, considerando aspectos textuais, melódicos e alguns tópicos especiais (acordes com sexta, a estética blues, acordes híbridos etc.).

### Artigos
#### Entropia, o Espaço Harmônico Probabilístico e a harmonia de Antonio Carlos Jobim
Carlos de Lemos Almada e Hugo Carvalho

Musica Theorica, v. 8 n. 1 (DOI: [https://doi.org/10.52930/mt.v7i1.202](https://doi.org/10.52930/mt.v7i1.202))

**Resumo**: Este artigo introduz um arcabouço teórico derivado de uma profunda e detalhada análise harmônica da integral de canções de Antonio Carlos Jobim, considerando aspectos "semânticos" (relacionado à ideia de tipos acordais) e "sintáticos" (envolvendo relações binárias entre acordes contíguos). O foco do estudo concentra-se na investigação das correlações existentes entre estilo composicional (no caso, relacionado à construção harmônica) e os conceitos de probabilidade, expectativa e, especialmente, entropia, definida como a medida da incerteza de eventos decorrentes no tempo. Após uma revisão bibliográfica sobre tais tópicos e de suas aplicações em música, uma seção dedicada a Cadeias de Markov prepara o exame central do objeto de estudo, a saber, as relações harmônicas “semântico-sintáticas” levantadas estatisticamente no repertório analisado das canções jobinianas. A formalização de um espaço harmônico probabilístico e do conceito de índice probabilístico, diretamente associados à entropia medida referente ao comportamento dos acordes das canções abrem uma perspectiva analítica original, permitindo ainda a generalização do aparato teórico-metodológico para o exame de outros repertórios e posterior comparação, apresentando-se, portanto, como um novo meio de investigação sobre a natureza do estilo.

#### DCnet: Uma representação espacial de cadeias de dominantes consecutivos
Carlos de Lemos Almada e Max Kühn

Vórtex, v. 10 n. 2 (DOI: [https://doi.org/10.52930/mt.v7i1.202](https://doi.org/10.33871/23179937.2022.10.2.7122))

**Resumo**: O presente artigo, derivado de uma pesquisa mais ampla, examina detalhada e sistematicamente o emprego de variantes de cadeias de dominantes consecutivos em um corpus de obras compostas por Antonio Carlos Jobim. A elaboração de um modelo teórico formado por um conjunto de premissas, conceitos, tipologias e ferramentas analíticas permite a classificação das variantes e sua plotagem em um esquema gráfico planar denominado DCnet, no qual retângulos representam acordes de qualidade “dominante com sétima”, dispostos de acordo com três eixos básicos. Tal estratégia evidencia a considerável multiplicidade de alternativas (especialmente aquelas não normativas) presentes no repertório. Estudos futuros derivados da presente proposta estão nos planos, tanto para investigar as razões dessa diversidade, quanto para generalizar o modelo, considerando outros repertórios.

### Apresentações em congressos

## 2021

### Artigos
#### Relações de simetria na estrutura de Eu te amo, de Antonio Carlos Jobim e Chico Buarque de Holanda
Carlos de Lemos Almada

Orfeu, v. 6 n. 1-3 (DOI: [https://doi.org/10.52930/mt.v7i1.202](https://doi.org/10.5965/2525530406032021080))

**Resumo**: Este artigo propõe uma análise detalhada
da estrutura de alturas da canção Eu te amo,
de Antonio Carlos Jobim e Chico Buarque
de Holanda, através de uma adaptação da
metodologia schenkeriana com ferramentas
originadas na chamada Teoria PósTonal. Busca-se evidenciar as complexas
relações de simetria que caracterizam a
peça, baseadas na interação das classes
intervalares 1, 5 e 6. Após uma avaliação
analítica do texto da canção e de sua forma
poética, o que estabelece uma base para o
subsequente exame das correlações entre
música e poesia, o artigo apresenta uma
discussão sobre os problemas associados
ao emprego da teoria schenkeriana nas
músicas pós-tonal e popular, suportada pela
literatura sobre o assunto (STRAUS , 1987;
LERDAHL, 1989; FORTE, 1995; McGOWAN,
2008; LARSON, 1998; 2009, entre outros). A
análise que se segue revela a extraordinária
infraestrutura simétrica (que se projeta em
diversos níveis de organização) sobre a qual é
construída a canção, o que inclui interações
com o argumento poético. Conclui-se
que, embora não perfeitamente ajustada
aos modelos da Ursatz schenkeriana, a
estrutura complexa e estratificada de Eu
te amo deriva de uma lógica particular,
consistente em relação a exemplares
de similar natureza da obra jobiniana.

#### Composição algorítmica de progressões harmônicas ao estilo de Antonio Carlos Jobim através de processos markovianos
Ana Miccolis, Claudia Usai, Eduardo Cabral, João Penchel, Igor Chagas, Max Kühn, Vinicius Braga e Carlos de Lemos Almada

Musica Theorica, v. 6 n. 1 (DOI: [https://doi.org/10.52930/mt.v6i1.175](https://doi.org/10.52930/mt.v6i1.175))

**Resumo**: O presente artigo é vinculado a uma pesquisa recentemente concluída, destinada
à análise da obra de Antonio Carlos Jobim (1927–1994) focando nas relações harmônicas. O
desenvolvimento metodológico da pesquisa foi efetivado em dois estágios: análise assistida
por computador e coleta estatística dos dados analisados. O processo analítico foi
estabelecido em um quadro teórico-metodológico (denominado *Sistema J*), cujas bases são
descritas em detalhes em trabalho recente (Almada *et al.* 2019a). Princípios, procedimentos
e conceitos originais, entre os quais qualidade-classe e relação binária, embasaram a
produção de dados. O principal objetivo deste trabalho é apresentar uma das aplicações
composicionais advindas do processamento e discussão dos dados obtidos ao longo do
mapeamento estatístico. Trata-se de *JobKov*, um software destinado à composição algorítmica
de progressões acordais originais estilisticamente jobinianas por intermédio de processos
estocásticos markovianos. O artigo apresenta e descreve os algoritmos criados e a estrutura
do programa, discutindo ainda como fatores estatísticos são cruciais para a determinação de
estilos composicionais.

## 2020

### Artigos

#### A Theory for Parsimonious Voice-Leading Classes
Carlos de Lemos Almada

Musica Theorica, v. 5 n. 2 (DOI: [https://doi.org/10.52930/mt.v5i2.139](https://doi.org/10.52930/mt.v5i2.139))

**Resumo**: Este artigo apresenta um modelo teórico-analítico destinado ao exame de conduções de vozes em música popular, considerando especificamente progressões harmônicas caracterizadas por formações acordais densas e conexões melódicas econômicas, o que é perfeitamente epitomizado pelas composições de Antonio Carlos Jobim. Novos conceitos, tipologias, regras de preferência, terminologias e simbologias específicas, assim como um modelo analítico integrado fornece a fundamentação necessária para a elaboração de um sistema de classes de conduções de vozes parcimoniosas, o que forma o núcleo desta proposta. Aplicações analíticas são apresentadas na seção final do artigo, com o exame de excertos de composições de Jobim.

